project:
  type: book
  output-dir: docs

book:
  title: "OTESSA 2024 Schedule"
  version: "0.1.0"
  chapters:
    - index.qmd
    - part: "In-Person @ McGill University"
      chapters:
          - jun12.qmd
          - jun13.qmd
          - jun14.qmd
          - jun15.qmd
    - part: "Francais"
      chapters:
      - jun12.qmd

comments:
  hypothesis: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-depth: 0
    toc-depth: 4
  pdf:
    documentclass: scrreprt



