project:
  type: book

book:
  title: "2024"
  author: "Norah Jones"
  date: "4/13/2024"
  chapters:
    - index.qmd
    - jun12.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
    number-depth: 0
  pdf:
    documentclass: scrreprt



