# Thursday, June 13 {.unnumbered}

::: {.callout-tip}
## Note!
IN PERSON at Campus de Longueuil of Université de Sherbrooke
:::

## Current time in Montréal (click for more info)

<iframe src="https://free.timeanddate.com/clock/i98z8zgl/n165/fs18/tcccc/ftbi/tt0/tw1/tm1/ta1" frameborder="0" width="347" height="23">

</iframe>
<!--
 Join us at the #OTESSA24 Morning Radio Show Monday, Tuesday, Wednesday, May 29, 30, and 31 from 6:30 – 7:30 am (Eastern) at https://voiced.ca
-->

## 10:00 - 10:30 | Continental Breakfast Provided {.unnumbered}

## 10:30 | National Digital Inclusion Round Table

**La Jonction A+B (3630 and 3635)**

- Welcome and Greetings (5 mins) | **ADM Edwards**
- International Best Practices: Where Does Canada Stand? (7 mins) | **Antonio Roque**
- Scientific Committee Study – Key Results (7 mins) | **Normand Roy (udeM)**
- National Inclusion Network Survey – Key Findings (5 min) | **Emmanuella Michel (Analyst with CFSC)**

## 10:58 | (NDIN) Transition

## 11:00 - 12:00 | (NDIN) Breakout Sessions

- 3 parallel groups with 6 facilitators
- 3 key questions (Issues, Best Practices, and Solutions)
- 3 key dimensions (Accessibility, Connectivity, and Digital Literacy)

## 12:00 - 1:00 | (NDIN) Lunch and Networking

## 1:00 - 1:50 | (NDIN) Plenary Session

- Reporting (3 min each) |  **6 facilitators**
- Conclusion (7 mins) | **Michael Langelier & Valerie Irvine**
- Next Steps (5 mins) | **Michael Langelier**
- *National Digital Inclusion Network* Launch

## 2:00 - 3:00 | Break and Networking


## 3:00-4:00 | Concurrent Session 5

### Session 5.1 | Sustaining Positive Change

####  An e-Book of One's Own: Empowering Student Learning Journeys 

**Room 3605 (Session A)**

**Practice**

**Terry Greene & Christian Metaxas** | *Trent University*


::: {.callout-note collapse="true"}
## Abstract
Join our interactive session to explore the transformative initiative, "An e-Book of One's Own," designed to reshape the student experience in higher education. In a dynamic environment, participants will engage with Pressbooks, a powerful tool enabling students to craft personalized e-books showcasing their academic journey. The session emphasizes hands-on exploration, collaborative problem-solving, and interactive structures to work towards successful implementation. Reflective exercises simulate the student experience, fostering a deep understanding of the program's impact. This session is not a passive presentation; it's a collective effort to redefine educational experiences. Attendees will leave with practical insights, strategies for implementation, and a renewed vision for empowering students through digital innovation.

:::

### Session 5.2 | Transitions of Online Learning and Teaching

####  Sustaining Community: Insights from Collaborative Approaches in Blended Course Design

**Room 3665 (Session B)**

**Practice**

**Brian Lorraine** | *Simon Fraser University*

::: {.callout-note collapse="true"}
## Abstract

This session presents findings from a comprehensive evaluation of a Faculty Learning Community (FLC) model implemented by the Centre for Educational Excellence (CEE) at Simon Fraser University (SFU), aimed at fostering blended learning practices. Building upon preliminary observations shared at OTESSA '23, the session delves into the nuanced challenges and insights gleaned from 5 semester-based cohorts over a 3-year period. Through focus group discussions and qualitative analysis of transcripts, the results uncover diverse perspectives on logistical, operational, and pedagogical considerations surrounding blended learning adoption. These insights are particularly timely given the growing trend towards blended/hybrid learning in Canadian post-secondary education, juxtaposed with faculty concerns over workload and burnout (Johnson, 2023). By exploring the implications of sustaining shared futures in higher education, this session invites participants to engage in a critical dialogue on navigating organizational practices centered on intentionality, community, and well-being.

:::


<!--
**Trottier 0060 (Session A) | Practice (French)**



 



### Session 5.2 | 






## 10:30-11:00 | Break

  
## 11:00-12:00 | Concurrent Session 6 | Ethics in Design Showcase

**All Session 6 Showcases are in the Trottier Mezzanine**


### Showcase 6.1 | Sustaining Positive Change

#### Redesigning Computing for Openness - the Ethics of Consuming Devices 

**Brian Sutherland** | *University of Toronto*


::: {.callout-note collapse="true"}
## Abstract

Have you started to accumulate old computing devices?   Why does the logic of computing involve repeated purchase and consumption of expensive "molded plastic epics" (Gabrys, 2011)?  Thinking back on calculation devices and this ethical problem of repeated consumption, the simple solar calculator stands out for its durability -- an energy harvesting strategy that doesn't use batteries, and it doesn't wear out.  Fifty year old solar powered calculators and other electronic devices which still work may be found. In this session, proposed for the Ethics in Design Conference Strand, I will review the history of energy harvesting information devices and their significant characteristics around sustainability, present response designs which engage various ethical questions around consumption, carbon production and degrowth, and discuss their usefulness as open designs and thought-artifacts in an iterative speculative design conversation around climate change.
:::

### Showcase 6.2  | Sustaining Positive Change

####  A framework and model for engagement in open, online spaces


**Michelle Harrison** | *Thompson Rivers University*

**Michael Paskevicius** | *University of Victoria*


::: {.callout-note collapse="true"}
## Abstract

This design case provides an analysis of the creation of an innovative open educational practices (OEP) project “Rethink Learning Design”, designed to explore and implement critical approaches to learning and instructional design. We recognized that if we want to embrace the power of OEP to change teaching and learning practice we need to enable spaces that honor multiple voices and perspectives, co-create knowledge and challenge traditional roles and hierarchies supported in open pedagogical approaches. Two key goals guided our project: the development of a reader/resource based on open pedagogy principles, emphasizing inclusivity and participation, and the integration of a reflective practice framework to deepen engagement and bring about a shift in educational practices. In this session and design case we will outline our iterative design process, ethical considerations, and theoretical foundations, and student use and feedback, with the aim of sharing insights and templates for practitioners in diverse educational contexts. We will consider how we can approach design as a theory of action and consider ways to promote learner ownership, open scholarship, anonymity, and options for permanence through our learning design tool.

:::

### Showcase 6.3  | Addressing Inequities

#### Cultural Dimensions of Ethics in Design: Indigenous Knowledge & Online Course Media



**Brian Lorraine** | *Simon Fraser University*


::: {.callout-note collapse="true"}
## Abstract
This session delves into the intricate design process of an online Indigenous Ethnozoology course, exploring the tensions, challenges, and ethical considerations encountered during an 8-month redesign and development period. Originally authored by a Squamish knowledge holder, the course featured recorded lectures intertwining oral histories with western scientific perspectives. The transition to a new instructor, a professor of white settler descent, prompted critical reflection on retaining Indigenous knowledge while improving instructional effectiveness. Drawing on cognitive load theory and empirical studies on video engagement, the design team navigated the complexities of honoring oral traditions while enhancing student learning experiences. This case study highlights the necessity for robust frameworks addressing Indigenous knowledge protocols in educational design, underscored by ongoing critical reflection to confront colonial legacies and promote ethical practices.

:::

### Showcase 6.4  | Addressing Inequities

#### Moving Towards Design Justice through Multivocal Design in Health Education

**Danielle Dilkes** | *University of Western Ontario*


::: {.callout-note collapse="true"}
## Abstract
This Design Case features an interprofessional stroke care case for health and medical education that was developed through a participatory design process. The objectives of the case were to highlight the complexities of interprofessional care and prepare learners for interprofessional practice. The approach to developing this case draws on key Design Justice principles: those most impacted by a design should be central in the design process and that various types of expertise exist and have value. The stroke care case was co-developed with patients, or Lived Experience Experts (LEEs), and all members of an interdisciplinary stroke care team, or Subject Matter Experts (SMEs). Patients were invited to share their real experience of stroke care, which became the basis of the case. Each health care professional was given full control over how their roles were portrayed, and invited to craft and star in their scenes within the case. This process resulted in a multivocal media rich case that more accurately reflects real patient experience and the real scope of practice for different health professionals. In our Design Case Exhibit, we will share multimedia components of the final case, but we will also share design knowledge in support of a more general framework for participatory design that could account for some of the complications of co-design across institutional roles.

:::

## 12:00 - 1:30 | Break

## 1:30 - 2:15 | Concurrent Session 7 

**Trottier 2100 (Session C)**



###  Session 7.2 | Wildcard & Transitions of Online Learning and Teaching

**Trottier 2110 (Session D)**



#### 1:55 - 2:15 | Using AI to design a Culturally Responsive STEM course and improve sense of belonging among students

**Research**

**Nahid Pourdolat Safari & Behnoosh Khoramrooz** | *University of Victoria*

::: {.callout-note collapse="true"}
## Abstract

This session aims to explore the integration of AI in Culturally Responsive Teaching (CRT) to enhance the sense of belonging in STEM education. Focusing on the importance of CRT in developing a sense of belonging and as a result, in enhancing motivation, engagement, persistence and academic performance, this presentation will discuss the theoretical foundations of CRT and explore implementing AI-generated content in STEM course design to foster a more inclusive learning environment. This session will delve into how AI can validate and acknowledge students' cultural backgrounds in STEM classes with a focus on underrepresented groups, including Indigenous, Black and international students. By showcasing practical examples, this session intends to demonstrate how AI technologies can be used to motivate and engage STEM students from diverse cultural backgrounds by improving their sense of belonging.
:::

## 2:15 - 2:45 | Break with Coffee & Snack Provided

## 2:45 - 3:45 | Posters - Forthcoming

## 3:45 - 4:00 | Break 

## 4:00 - 4:30 | Concurrent Session 8


### Session 8.1  | Addressing Inequities 

**Trottier 2100 (Session C)**



### Session 8.2  | Addressing Inequities

**Trottier 2110 (Session D)**

####  Protecting Indigenous Knowledge in Open Education

**Don Eldridge & Mary Gu** |  *eCampus Ontario* 


::: {.callout-note collapse="true"}
## Abstract
As open educational practices (OEP) and open educational resources (OER) grants, programs, and initiatives are created by organizations, there is a need to consider the diverse and nuanced Equity, Decolonization, Diversity, and Inclusion (EDDI) issues that will be surfaced. Funding institutions and agencies must consider how their support and promotion of OEP and OER may not support and may even alienate Indigenous members of their community. This presentation will provide an overview of the EDDI concerns faced in a major investment into an OER program in Canada that impacted multiple postsecondary institutions through 3 years of work. This presentation will share the development process of a geographically specific Commons license, the metrics on uptake since the launch of the license, and the impact on supporting digital-by-design virtual learning. This experience can inform the broader open education community by sharing lessons learned and best practices as a case study.  

:::

### Session 8.3  | Sustaining Positive Change

**Trottier 0060 (Session A)**



## 5:00 - 7:00 | See Congress Programming for Social Zone & Food Options
-->

## To Be Determined | OTESSA Social
