# Friday, June 14 {.unnumbered}

::: {.callout-tip}
## Note!
IN PERSON at Campus de Longueuil of Université de Sherbrooke
:::

## Current time in Montréal (click for more info)

<iframe src="https://free.timeanddate.com/clock/i98z8zgl/n165/fs18/tcccc/ftbi/tt0/tw1/tm1/ta1" frameborder="0" width="347" height="23">

</iframe>



## 8:30 - 9:30 | Unconferencing Breakfast (Continental Breakfast Provided){.unnumbered}

**La Source**

Internet Radio Feeds Available: <a href="https://radio.uvic.ca/public/otessa" target="_blank" class="badge bg-primary"><b> Audio Stream 1</b></a> <a href="https://radio.uvic.ca/public/otessa_2" target="_blank" class="badge bg-primary"><b>Audio Stream 2</b></a> <a href="https://radio.uvic.ca/public/otessa_3" target="_blank" class="badge bg-primary"><b>Audio Stream 3</b></a> <a href="https://radio.uvic.ca/public/otessa_4" target="_blank" class="badge bg-primary"><b>Audio Stream 4</b></a>

## 9:30 - 9:45 | Conference Welcome, Announcements, & Land Acknowledgement

**La Source**

<a href="https://radio.uvic.ca/public/otessa" target="_blank" class="badge bg-primary"><b>Audio Stream 1</b></a>


## 9:45 - 10:00 | Break


## 10:00-11:00 | Concurrent Session 6

### Session 6.1 | Transitions of Online Learning and Teaching

**Room 3675 (Session A)**

<a href="https://radio.uvic.ca/public/otessa_3" target="_blank" class="badge bg-primary"><b>Audio Stream 3</b></a>


#### 10:00 - 10:30 | How do students make sense of a Learning Analytic Dashboard? Exploring learners’ perceptions and plans

**Research**

**Mariel Miller & Emma Graves** | *University of Victoria*

::: {.callout-note collapse="true"}
##### Abstract

Student-facing learning analytic dashboards (LADs) claim to help students manage their learning. However, many widely available LADs can be inflexible and lack consideration of the contemporary theory and research of learning. Furthermore, it is unclear how students use information presented in LADs and translate it into meaningful action. This descriptive study investigates students’ use of a learning analytic dashboard to inform goal-setting and achievement over the course of one week in a large, hybrid undergraduate course. Specifically, we explore (a) learners’ evaluations of their course progress after interacting with the LAD (b) types of goals set by students for managing their learning during the week, post-interaction with the LAD; (c) the extent to which learners achieved their goals; and (d) students' perceptions of LAD utility in supporting them to manage their learning. Data were collected through two questionnaires administered at the midpoint of a course. Preliminary findings indicate that after viewing the dashboard, most learners set goals for maintaining their current progress during the week by focusing on their motivation. However, most learners reported failing to fully attain their goal by the end of the week. Implications for supporting learner engagement with LADs students-facing learning analytic dashboards are discussed.
:::

 
#### 10:30 - 11:00 | Tech-based teaching practices and student engagement from the perspective of self-determination theory

**Research**

**Géraldine Heilporn, Mourad Majdoub & Fatme Diab** |  *Université Laval* 

::: {.callout-note collapse="true"}
##### Abstract
Teachers can enhance inclusion and provide personalized learning experiences for students by utilizing digital tools and prioritizing inclusive teaching methods (Kim et al., 2019). However, Cabellos et al. (2023) have argued that digital resources were used more to transmit information than to engage students in their learning. The widespread and necessary use of ICT has not served to make learning student-centered but was primarily aimed at the transmission and evaluation of the content. Thus, students’ motivation and engagement are significantly affected, worsening the existing issues regarding low school motivation, especially in secondary school (Caiet al., 2022). In response to these research gaps, the aim of this communication is to explore high school teachers’ technology-based teaching methods that motivate and address the needs of learners with the use of technology based on the digital divide framework (Van Dijk, 2020), SDT (Self-Determination Theory) (Ryan & Deci, 2017) and student engagement model (Archambault et al., 2019). We have conducted individual semi-structured interviews with high school teachers aiming to obtain in-depth qualitative data mainly through open-ended questions. A thematic analysis has been employed to inductively analyze the interview data and generate possible themes and categories based on the objectives of our study. The findings and recommendations for future research will be shared at OTESSA conference.

:::

### Session 6.2 | Sustaining Positive Change

**Room 3665 (Session B)**

<a href="https://radio.uvic.ca/public/otessa_4" target="_blank" class="badge bg-primary"><b>Audio Stream 4</b></a>


#### 10:00 - 10:20 | Considering a Reboot: Using Design-Thinking Strategies to Maintain a Dynamic, Industry-Relevant, Game Design Curriculum

**Research**

**Christopher Marsh** | *Bradley University*

**Bruce Parsons**  | *Radford University*

::: {.callout-note collapse="true"}
##### Abstract

The gaming industry, expected to exceed $300 billion in global revenue by 2025, offers unique challenges and opportunities for academic programs and the traditional collegiate curriculum development process. This research discusses how game design curricula can evolve to meet those demands through sustainability and preparing graduates to be skilled and conscious of their impact and opportunities in the field.


:::


#### 10:20 - 11:00 | Walk the Walk: Fostering Equitable Practices in Organizational Sustainability

**Practice**

**Apurva Ashok & Kaitlin Schilling** | *The Rebus Foundation*

::: {.callout-note collapse="true"}
##### Abstract

How do equitable practices show up in the workplace? In our pursuit of different goals, we often forget the journey and careful, collective organization it takes to get and hold us there.

In the discourse around building equitable futures, this session makes space to think about organizational sustainability and designing intentional work practices for long-lasting and widespread impact. Our approach extends beyond addressing external stakeholders and emphasizes modeling equitable practices internally — at the individual level and collectively within the organization. 

The presentation will delve into the flexible work model we have developed that prioritizes organizational mission and the people and work to implement the mission. Our model looks at goals beyond just profitability and instead asks how we can sustain individuals, foster critical reflection, and create positive organizational change. We will showcase how equitable practices manifest in daily team interactions, board discussions, strategic direction, programming, and resource utilization.  

While the principles we embrace are not groundbreaking, they are critical to the welfare and long-term success of an organization. Our focus is intentionally on the often-overlooked aspect of applying equity-minded principles within the organizational context. The presentation aims to cement the significance of iterative daily practices in sustaining a culture of equity and inclusion within educational organizations.

:::



## 11:00 - 11:30 | Break


## 11:30 - 12:30 | Concurrent Session 7

### Session 7.1 | Addressing Inequities

**Room 3675 (Session A)**

<a href="https://radio.uvic.ca/public/otessa_3" target="_blank" class="badge bg-primary"><b>Audio Stream 3</b></a>


#### 11:30 - 12:30 | Is AI for or Against Human Success? An Exploratory Engagement by Female Scholars

**Practice**

**Judith Pete** | *Tangaza University College*

**Gelareh Keshavarz** | *Athabasca University*

**Jenni Hayman** | *Royal Roads University*


::: {.callout-note collapse="true"}
##### Abstract

In this practice-focused session, an educator from Kenya and two educators from Canada will compare access to and experiences of artificial intelligence (AI) tools for work and education in their professional contexts. Topics will include learner, educator, and institutional access to the Internet and devices in general–and access and use of AI tools, specifically. The presenters will share emerging concerns about the ethics of the design and use of AI tools and share their interests and the positive potential they see for the use of these tools. Participants attending the session will be invited to share their ideas, contexts, interests, and concerns about AI as contributions to group learning. Strategies for ethical and pedagogic review of AI tools will be shared.

:::

### Session 7.2 | Addressing Inequities

**Room 3665 (Session B)**

<a href="https://radio.uvic.ca/public/otessa_4" target="_blank" class="badge bg-primary"><b>Audio Stream 4</b></a>


#### Unleashing Potential: Exploring Open Education Initiatives with TRU Open Press

**Practice**

**Marie Bartlett, Brenna Clarke Gray, Danielle Collins, Jessica Obando Almache, Kaitlyn Meyers, Ananya Kamboj, Jon Fulton, & Michelle Harrison** | *Thompson Rivers University*

::: {.callout-note collapse="true"}
##### Abstract
Join us at the OTESSA conference as we highlight the transformative impact of the Thompson Rivers University (TRU) Open Press. As proponents of open education, we aim to demonstrate how the TRU Open Press fosters a sustainable and inclusive future through innovative projects. Gain insights into our core operations, including our role as a leading provider in web-first publishing, open pedagogy, and scholarship. We'll delve into our proposal process, detail how projects are initiated and navigated, with the goal of sustaining positive change for a diverse, sustainable, and democratic world. Experience the tangible impact of our initiatives through a showcase of successful projects in the evolving landscape of online learning. Explore our open publication strategies, funding mechanisms, and their profound impact on addressing inequities. Learn about our collaborations with faculty, students, Indigenous communities, and local organizations, all contributing to sustaining shared futures through education. Delve into the production processes of our Open Educational Resources (OER) and open pedagogy projects, fostering positive and meaningful change. Join us in shaping the future of education and scholarship through meaningful discussions and building connections for shared knowledge and inclusivity.
:::

## 12:30 - 1:30 | Lunch Break

There are multiple options in the Main Floor food court and an outside patio on the third floor where we can gather for lunch.

## 1:30 - 3:00 | Concurrent Session 8

### Session 8.1 | Wildcard

**Room 3675 (Session A)**

<a href="https://radio.uvic.ca/public/otessa_3" target="_blank" class="badge bg-primary"><b>Audio Stream 3</b></a>


#### 1:30 - 2:00 | Dangling in Between: Investigating the Impacts of Using AI in Higher Education Research

**Research** 

**Todd Milford & Sara Fallahi** | *University of Victoria*


::: {.callout-note collapse="true"}
##### Abstract

Artificial intelligence (AI) is used in education since 2015 (Vincent-Lancrin & van der Vlies, 2020). Benefits and hindrances of using AI has been debated in many academic literature (Chen et al., 2020; Crompton & Song, 2021; Verma & Tomar, 2021). Today with the rise of AI tools which are available to the public, with students using them more, and universities clarifying their stance on the topic, investigating the impacts of using AI in education is more crucial than ever. The purpose of this paper is to investigate the impacts of using AI tools for graduate students. For this aim, participants were introduced to a few AI tools to use for writing literature review. Participants were also interviewed on their experience and opinion on using AI in research. Initial findings of this research suggest that the participants could benefit from using AI, for example in saving time while researching, although some concerns remained unsolved for them. The output of this research can be considered while integrating AI in higher education as well as policy making.
:::

#### 2:00 - 2:30 | OER in the context of generative AI

**Practice**

**Normand Roy** | *University of Montreal*

::: {.callout-note collapse="true"}
##### Abstract
This proposal explores the transformation of OER in the context of Artificial Intelligence (AI), examining the multifaceted relationship between these two domains. While highlighting the potential benefits of AI in personalizing learning, creating new resources, and enhancing accessibility, the proposal also confronts the challenges associated with authorship and ethical considerations of AI-generated content. Focusing on strategies to navigate these challenges while ensuring the integrity of original contributions, the proposal further investigates how advanced AI techniques like fine-tuning and Retrieval Augmented Generation (RAG) can be employed to create highly adaptive and personalized OER aligned with learners' needs. Additionally, it explores the potential of AI in generating multimodal resources, potentially overcoming language, literacy, and learning preference barriers to broaden access to education globally. Ultimately, this proposal aims to leverage AI while addressing its inherent challenges, ultimately enhancing the quality, accessibility, and adaptivity of OER.
:::


####  2:30 - 3:00 | Undergraduate Students as Research Partners: Lessons Learned in a Scoping Review of Social Media in Teaching and Learning

**Research**

**Emma Duke, Linh Bui, Richard Hayman, & Erika E. Smith** | *Mount Royal University*


::: {.callout-note collapse="true"}
##### Abstract

After 20+ years of educators incorporating various social media into their undergraduate teaching and learning, we have identified the need to critically examine the existing body of literature on social media integration in higher learning to understand how this use has been studied as well as how it informs today’s teaching and learning processes. This presentation reports on our scoping review project exploring trends, gaps, and issues in the use of social media technologies in undergraduate teaching and learning contexts. The researchers, including two undergraduate student research partners, will refer to the project protocol (author3 & author4, 2023) and present initial findings and lessons learned during the project to-date. We will also discuss meta-research implications from these initial findings, including an exploration of partnering with undergraduate student RAs on a rigorous evidence synthesis project, with the latter delivered primarily from the perspective of the student partners.

:::

### Session 8.2  | Transitions of Online Learning and Teaching 

**Room 3665 (Session B)**

<a href="https://radio.uvic.ca/public/otessa_4" target="_blank" class="badge bg-primary"><b>Audio Stream 4</b></a>


####  1:30 - 2:00 | Creating Reskilling and Upskilling Opportunities for Internationally Educated Immigrants through Online Learning Programs: The Story of Success

**Practice**

**Marina Grineva** | *Intercultural Skills Lab (Rotman School of Management, University of Toronto)*

::: {.callout-note collapse="true"}
##### Abstract
The importance of access to reskilling and upskilling opportunities for immigrants can’t be overestimated. However, there is a number of challenges that this population faces while trying to integrate into the workforce or advance in their careers in Canadian work environments. One of such challenges is the inability to attend professional development programs in-person. From this perspective, technology-enhanced learning, specifically, on-line or hybrid learning environments (a combination of asynchronous and synchronous learning sessions) are one of the solutions of the problem.

In this presentation, we aim to provide the overview of  professional development programs offered by [The Intercultural Skills Lab](https://www.rotman.utoronto.ca/ProfessionalDevelopment/interculturalskillslab) (Rotman School of Management, University of Toronto) that successfully provides reskilling and upskilling opportunities for internationally trained immigrants by creating a variety of technology-enhanced learnings environments. Specifically, we will demonstrate how through the use of a number of online learning tools the program participants are given an opportunity to become part of vibrant collaborative learning communities fostering professional development in such areas as intercultural intelligence, effective communication, career management, as well as in the sector-specific disciplines.
:::


#### 2:00 - 2:30 | Flexibility and Foresight in Ontario Postsecondary Education: Voices from the Field

**Practice**

**Elisa Arnold, Rocio Chavez Telleria & Laura Viselli** | *eCampusOntario*

::: {.callout-note collapse="true"}
##### Abstract
Flexibility has emerged as a key area to support digital transformation in postsecondary education, and educators are often at the forefront of implementation. To understand how educators are thinking and feeling, we engaged with 45 educators from Ontario's publicly-supported postsecondary institution through six virtual workshops using foresight methods to frame the conversations. Foresight is a formal, systematic way of thinking about the future, which offers a way to think about how the future might play out and expand the solution space. Specifically, we used the following foresight methods: Futures Triangle, to understand the interrelationships among future visions, present drivers of change, and past limitations; Causal Layered Analysis (CLA), to explore the assumptions that underlie the way we frame problems, situations, and solutions; and Three Horizons, to explore what would it take to transition from present situations to future visions. This presentation is a summary of the research about these educators think and feel about flexibility in post secondary education, including considerations of equity and ethics and the application to practice, policy and infrastructure and recommended next steps.
:::



**Room 3665 (Session B)**

#### 2:30 - 3:00 | Developments in National OER Advocacy in Canada 

**Practice**

**Ann Ludbrook** | *Toronto Metropolitan University*

**Michael McNally** | *University of Alberta*

::: {.callout-note collapse="true"}
##### Abstract

This 50-minute session builds upon the Canadian Association Research Libraries (CARL)’s National Advocacy Framework for Open Educational Resources (OER) in Canada (2023). It updates attendees on national OER advancements, and features insights from the Indigenous Knowledges and OER summit held in Vancouver in February 2024. The summit produced principles for working with Indigenous knowledges in OER, alongside discussions on progressing national OER advocacy. The session covers developments in policy, infrastructure, and francophone OER stemming from summits in 2022 and 2023. Reports from these events will be discussed, along with updates on ongoing federal budget consultations and the anticipated 2025 federal election. The audience will also have the opportunity to contribute ideas and strategies for national advocacy, via group discussion and polls.
:::

## 3:00 - 3:30 | Break

## 3:30 - 4:30 | Concurrent Session 9 

### Session 9.1  | Addressing Inequities

**Room 3675 (Session A)**

<a href="https://radio.uvic.ca/public/otessa_3" target="_blank" class="badge bg-primary"><b>Audio Stream 3</b></a>


#### Challenging Stereotypes: The Role of The Matilda Project in STEM Gender Equality

**Workshop**

**Shehroze Saharan** | *University of Guelph*

::: {.callout-note collapse="true"}
##### Abstract

The Matilda Effect - a term coined by Yale historian Margaret W. Rossiter - is a phenomenon used to describe women scientists who have been ignored, forgotten, or denied credit due to sex-linked biases. The unfortunate reality is that the Matilda Effect is still prevalent today as women are not given due credit for their scientific achievements. The Matilda Project (https://www.thematildaproject.com/), a higher education initiative committed to shedding light on the pervasive issue of gender inequality in STEM, stands strategically poised to tackle this challenge. Positioned as an open-access resource, The Matilda Project encompasses the creation of educational videos and a website. The videos offer concise insights into key topics, while the website will host interactive activities and will serve as a comprehensive collection showcasing both historical and contemporary women scientists who share a common experience—the Matilda Effect.

:::

### Session 9.2 | Sustaining Positive Change

**Room 3665 (Session B)**

<a href="https://radio.uvic.ca/public/otessa_4" target="_blank" class="badge bg-primary"><b>Audio Stream 4</b></a>


#### 3:30 - 3:50 | Using AI to design a Culturally Responsive STEM course and improve sense of belonging among students

**Research**

**Nahid Pourdolat Safari & Behnoosh Khoramrooz** | *University of Victoria*

::: {.callout-note collapse="true"}
##### Abstract

This session aims to explore the integration of AI in Culturally Responsive Teaching (CRT) to enhance the sense of belonging in STEM education. Focusing on the importance of CRT in developing a sense of belonging and as a result, in enhancing motivation, engagement, persistence and academic performance, this presentation will discuss the theoretical foundations of CRT and explore implementing AI-generated content in STEM course design to foster a more inclusive learning environment. This session will delve into how AI can validate and acknowledge students' cultural backgrounds in STEM classes with a focus on underrepresented groups, including Indigenous, Black and international students. By showcasing practical examples, this session intends to demonstrate how AI technologies can be used to motivate and engage STEM students from diverse cultural backgrounds by improving their sense of belonging.


:::

#### 3:50 - 4:30 | Empowering Student Voices: Integrating Stop-Motion Animation with Google Drawing, Canva, and Cap Cut

**Practice**

**Patricia Dennis** | *Pride Academy Charter School*


::: {.callout-note collapse="true"}
##### Abstract
In designing Project Based Learning (PBL) curriculum and units that focus on real-world issues related to diversity, sustainability, and justice, students will create hands-on projects that evoke change within themselves, their communities, and globally. In this interactive and engaging in-person workshop, educators will be immersed in a comprehensive session focused on harnessing the potential of stop-motion animation using Google Draw, Canva, and Cap Cut. The central objective of this workshop is to empower educators with the expertise and tools to integrate the engineering design process into their teaching methods, fostering student creativity and innovation while amplifying their voices through modern technology. Throughout the workshop, participants will explore how to utilize Project-Based Learning (PBL) to sustain positive change and explore the UN Global Goals, aiming to equip educators with the necessary resources and strategies to facilitate meaningful learning experiences for their students.

:::
