# Wednesday, June 12 {.unnumbered}

::: {.callout-tip}
## Note!
IN PERSON at Campus de Longueuil of Université de Sherbrooke
:::

## Current time in Montréal (click for more info)

<iframe src="https://free.timeanddate.com/clock/i98z8zgl/n165/fs18/tcccc/ftbi/tt0/tw1/tm1/ta1" frameborder="0" width="347" height="23">

</iframe>



## 8:30 - 9:30 | Unconferencing Breakfast (Continental Breakfast Provided){.unnumbered}

**La Source**

::: {.callout-important}
### Finding La Source

La Source is in the same building as the Metro Station. [We are on Floor B1 in the blue building on this map](https://www.usherbrooke.ca/decouvrir/fileadmin/sites/decouvrir/documents/contacter-udes/Plan-Campus-de-Longueuil-FR.jpg) in the back corner of the food court.

From the Metro:

- Walk under the scaffolding
- Turn right at the end
- La Source is the first door on the right
- Proceed to the right side of the food court
  
:::

Internet Radio Feeds Available: <a href="https://radio.uvic.ca/public/otessa" target="_blank" class="badge bg-primary"><b> Audio Stream 1</b></a> <a href="https://radio.uvic.ca/public/otessa_2" target="_blank" class="badge bg-primary"><b>Audio Stream 2</b></a> <a href="https://radio.uvic.ca/public/otessa_3" target="_blank" class="badge bg-primary"><b>Audio Stream 3</b></a> <a href="https://radio.uvic.ca/public/otessa_4" target="_blank" class="badge bg-primary"><b>Audio Stream 4</b></a>







## 9:30 - 9:45 | Conference Welcome, Announcements, & Land Acknowledgement

**La Source**

<a href="https://radio.uvic.ca/public/otessa" target="_blank" class="badge bg-primary"><b>Audio Stream 1</b></a>



## 9:45 - 10:00 | Break

## 10:00-11:00 | Concurrent Session 1

### Session 1.1 | Addressing Inequities

**Room 3675 (Session A) | Research** 

<a href="https://radio.uvic.ca/public/otessa_3" target="_blank" class="badge bg-primary"><b>Audio Stream 3</b></a>


#### Evolving our understanding of technology-integrated assessment: A review of the literature and development of a new framework


**Colin Madland** | *University of Victoria*  

**Valerie Irvine** | *University of Victoria*  

**Christopher DeLuca** | *Queens University*  

**Okan Bulut** | *University of Alberta*  

::: {.callout-note collapse="true"}
##### Abstract

In this paper, we review the literature on technology in assessment in higher education and compare how the literature aligns with the Assessment in a Digital World framework (Bearman et al., 2022). We found themes in the literature that were not present in the framework (e.g., academic integrity and faculty workload) and constructs in the framework not evident in the literature (e.g., future self and future activities). Additionally, we consider other gaps in both the framework and the literature evident in day-to-day practices and government legislation or mandates, such as considering legal or ethical aspects of duty of care and the integration of Indigenous worldviews. We then developed the Technology-Integrated Assessment Framework to help instructors and administrators consider a broader range of constructs when planning assessment strategies in technology-integrated learning environments and to serve as a basis for further investigation into how the different constructs within the framework contribute to how we design, implement, and teach about assessment in digital learning environments today. We present an introduction of this technology-integrated assessment framework, invite feedback from the OTESSA community, and discuss future research goals and opportunities.

:::

### Session 1.2 | Transitions of Online Learning and Teaching

**Room 3665 (Session B) | Research**

<a href="https://radio.uvic.ca/public/otessa_4" target="_blank" class="badge bg-primary"><b>Audio Stream 4</b></a>


#### Card Sorting as a Methodology for Discovering Underlying Needs of Communities Seeking to Develop Learning Spaces: Towards a Better Understanding of the Sociocultural Ecology


**Marguerite Koole** | *University of Saskatchewan*  

**Gordon Rugg** | *Keele University*  

**Thiago Lemes de Oliveira** | *Wolverhampton University*  

**Valentina Arancibia** | *Federal University of Uberlândia*  

**Redouane Touati** | *Universidad Católica del Maule & Yahia Fares University, Médea*  


::: {.callout-note collapse="true"}
##### Abstract

In this paper, we focus on a knowledge elicitation method called single-criterion card sorting. To begin, we will provide a background two of the communities with whom we have been working: a Deaf and Hard of Hearing community in Canada and a community in Algeria. After briefly describing the context of the project, we will provide a description of, rationale for, and challenges with card sorting as a preliminary method. Next, we will explain the card-sorting procedures, present the preliminary data, and explain the analysis procedures. Although there are many kinds of card sorting, we will guide participants through a hands-on exercise using single-criterion card sorting (using both digital and in person techniques). Participants will learn about text-based, image-based, and object-based options, when to use card sorting, how to collect data, and how to analyse card sorting data through visual-numeric ‘heat maps’ (co-occurrence matrices). We can share a free Java-based software tool for generating heat maps.

Put simply, the paper provides a discussion of the data and how the data will guide the selection of subsequent knowledge modelling methods that will guide further analysis and hopefully help to gain a better, in-depth understanding of the communities’ needs and aspirations that may otherwise remain hidden beneath social, cultural, and linguistic barriers. With careful selection of knowledge modelling methods, we hope to help limit bias and the perpetuation of English and Western ways of doing and knowing. Meaningful consultation and collaboration can help to ensure that the communities’ interests remain at the heart of the project(s) and reduce Western (‘outsider’) control of research, analysis, and development.
:::


## 11:00 - 11:30 | Break

## 11:30-12:30 | Concurrent Session 2 

### Session 2.1 | Wildcard

**Room 3675 (Session A)**

<a href="https://radio.uvic.ca/public/otessa_3" target="_blank" class="badge bg-primary"><b>Audio Stream 3</b></a>


#### 11:30 - 12:00 | Unveiling the Future of Language Teaching and Acquisition: Exploring the Conflation of Cultural Historical Activity Theory, and Generative AI

**Practice**


**Tanya Dixit & Michael Paskevicius** | *University of Victoria*

::: {.callout-note collapse="true"}
##### Abstract

Contemporary technology trends in education are profoundly reshaping the design of teaching and learning languages. This trajectory, Li (2017) observes, can be largely attributed to the "development of learning theories and pedagogical considerations" (p.3) alongside several other contributing factors, a sentiment echoed by Blake (2009) and Heift and Chapelle (2012) who confirm the far-reaching influence and potential of CALL, which further offers substantial promise to refine and enhance second language (L2) acquisition. Moreover, these scholars unanimously agree that technology integration and implementation should be firmly grounded in research built upon theoretical foundations. Hence, conjoining Cultural Historical Activity Theory (CHAT) (Engeström, 1987) and the affordances of generative AI, exemplified by ChatGPT, this presentation looks at transformative opportunities in which current AI bots can reform classroom teaching-learning discourse. This comprehensive awareness about AI's potentiality to revamp instructional methods, improve learner engagement, and offer avenues for personalizing and differentiating instruction is to be deemed essential not only for equipping stakeholders with the knowledge to navigate the nuances and challenges inherent in optimizing language acquisition experiences, but also to set the stage for a future where learners and educators can seamlessly integrate cutting-edge tools and technologies into improving the language acquisition experience. 

:::

#### 12:00 - 12:30 | Developing Scales of Learner Modality Preferences and Online Learning Acceptance and Early Results from a Province-Wide Study

**Research**

**Valerie Irvine & Mariel Miller** | *University of Victoria*

**Okan Bulut** | *University of Alberta*


### Session 2.2 | Sustaining Positive Change

#### 11:30 - 12:30 | Critical reflections on course materials: The rise of the single-use e-textbook and a university library’s multi-pronged response

**Room 3665 (Session B)**

<a href="https://radio.uvic.ca/public/otessa_4" target="_blank" class="badge bg-primary"><b>Audio Stream 4</b></a>


**Madelaine Vanderwerff & Sara Sharun** | *Mount Royal University*

::: {.callout-note collapse="true"}
##### Abstract

A recent shift by higher education publishers from print to digital content has led to an increase in course instructors adopting digital textbooks and courseware that are rented or sold directly to students. These digital courseware systems are attractive for a number of reasons: they are customizable, contain integrated value-added features, and are often marketed as inclusive, accessible, and cost-saving.  However, there is debate about the impact of these tools on student learning and success, and about the challenges they create for learners, including restricting, controlling, and monitoring access and use. 

Our library has undertaken a number of distinct but related initiatives to support faculty in transitioning away from commercial textbooks in their courses.  In this session, we will share a number of initiatives that invite faculty to critically reflect on course material selection, raise awareness about the challenges of commercial textbooks, and offer support for transitioning to OER, freely available, or library-licensed materials in their courses.  This session will share findings from our research and collaboration with stakeholders on campus.   
Participants will be invited to share their experiences and discuss the potential long-term impacts of, and responses to, the commercialization and commodification of learning materials on their campuses.

:::



## 12:30 - 1:30 | Lunch Break

There are multiple options in the Main Floor food court and an outside patio on the third floor where we can gather for lunch.

## 1:30 - 2:30 | Concurrent Session 3 


### Session 3.1 | Transitions of Online Learning and Teaching

**Room 3675 (Session A)**

<a href="https://radio.uvic.ca/public/otessa_3" target="_blank" class="badge bg-primary"><b>Audio Stream 3</b></a>

#### 1:30 - 2:00 | Personalized learning path in a course on digital technology for secondary education programs

**Practice**

**Géraldine Heilporn, Alexandre Lepage, Audrey Raynault & Julie Chamberland** | *Université Laval*

::: {.callout-note collapse="true"}
##### Abstract

This communication presents the new design of a course on digital technology for teaching and learning, offered to students enrolled in in secondary education programs at Laval University (Quebec), based on the concept of adaptive learning. Following a diagnostic assessment questionnaire of their digital competency at the beginning of the semester, students are automatically assigned to three thematic activities aimed to develop their digital competency for transfer to secondary education. After working on a thematic activity for one week, students return to the classroom for peer-to-peer teaching and learning on these thematic activities, in a blended course modality alternating asynchronous (thematic activities) and synchronous classes (peer-to-peer teaching and learning). Temporary thematic support communities as well as disciplinary learning communities are set to encourage peer collaboration and support throughout the semester. At given timepoints during the semester, students also have to assess their peer collaboration and give them feedback a peer evaluation mechanism.

:::

####  2:00 - 2:30 | Getting the right mix - A risk-based approach to blended learning design for healthcare workplace training

**Practice**

**Deborah Exelby** | *Athabasca University*

::: {.callout-note collapse="true"}
##### Abstract
Ensuring employees are competent and confident to perform their duties relies on new employee orientation and ongoing compliance training. Currently, there is no industry standard or evidence-informed decision framework that determines when to use face-to-face, online, or blended learning for healthcare workplace training. This thesis research investigates how instructional designers use blended learning to balance the ethical, patient safety, resource, and budget demands that an ever-changing and high-tech workplace creates, by answering the question: Is there a relationship between perceived risk of the content to be learned, delivery modes, and interaction techniques in healthcare workplace training? An online survey and correlation analysis was used to rank healthcare workplace instructional designers’ preferences about  their use of learning modalities and interaction techniques in relation to their perceived risk of the content to be learned. Quantitative analysis found: 1) no preference for synchronous delivery, 2) low preference for blended learning delivery, and 3) high preference for in-person face-to-face delivery via learner-instructor interaction specifically for high and medium-risk learning content. This study enabled the development of a proposed training and orientation planning support (TOPS) matrix for risk-based instructional design decision-making. 
:::

###  Session 3.2 | Addressing Inequities

**Room 3665 (Session B)** | *Practice*

<a href="https://radio.uvic.ca/public/otessa_4" target="_blank" class="badge bg-primary"><b>Audio Stream 4</b></a>

#### 1:30 - 2:30 | Designing Cyberinfrastructure for Knowledge Sharing: A Bioacoustics Case Study

::: {.callout-note collapse="true"}
##### Abstract

[FishSounds](https://fishsounds.net) is an online portal that provides open and user-friendly access to academic scholarship regarding the sounds made by fish species. It is the result of an international collaboration between students, scientists, and information professionals, and has become a resource used around the globe for research, education, journalism, and general interest. This website is just the first instance, however, of a new approach to sharing knowledge and an emerging cyberinfrastructure for open scholarship. The codebase behind FishSounds was designed to be reusable with other datasets, and in the coming years additional portals will connect users to knowledge from varied subject areas across academic disciplines. This presentation will discuss the development and reception of FishSounds as a case study for the creation of these websites, called Searchable Online Catalogues of Knowledge, or SOCKs. Topics of discussion will include defining and collecting a dataset; reaching and responding to diverse audiences; required resources and sustainability of the website; and how the concept of a ‘knowledge authority’ impacts citizen science and open scholarship. Attendees will have the opportunity to propose subject areas that would benefit from having a SOCK site as we seek partners and projects for an upcoming grant proposal.

:::


## 2:30 - 3:00 | Break

## 3:00 - 4:00 | Concurrent Session 4

### Session 4.1 | Sustaining Positive Change

**Room 3675 (Session A)**

<a href="https://radio.uvic.ca/public/otessa_3" target="_blank" class="badge bg-primary"><b>Audio Stream 3</b></a>


####  3:00 - 3:30 | Means to an End? Ethical Methodologies for Developing Ethical Facial Recognition Training Datasets


**Research**

**Jin Sol Kim, Amanda Yu, Lai-Tze Fan & Tatum Weicker-O'Connor** | *University of Waterloo*


::: {.callout-note collapse="true"}
##### Abstract
In January of 2020, The New York Times published a report on the implications of Clearview AI’s facial recognition system in law enforcement. However, unlike other discussions of facial recognition in this field, which focus on the consequences of racial biases within the system, this report revealed the problematic methodology behind the development of Clearview AI’s robust training dataset, calling for an examination of ethics in the very process of creating ethical tech. Clearview AI has since been banned in countries including Canada for scraping over three billion photos from social media platforms, breaching privacy laws surrounding consent for use of personal data. Yet the challenge remains: how can we create a fair and robust training dataset for facial recognition algorithms given the resource-intensive nature of the task as well as complications such as the limitations of data privacy? How can we ensure that the means of creating ethical facial recognition technologies mirror its ends?  With current rapid developments in generative AI, synthetic training datasets have newly emerged as a promising player in the field of facial recognition technologies. Training datasets such as Digi-Face 1M that are entirely composed of generated images seem to waive the need for ethical considerations altogether by skirting the use of human subjects. Nevertheless, insofar as the application of these tools affect human lives, we must question whether this new method of dataset development is truly free from ethical concerns.

:::

####  3:30 - 4:00 | Open Learning Design in an Inquiry-based Educational Setting

**Research**

**Maryam Shirdel Pour & Michael Paskevicius** | *University of Victoria*

::: {.callout-note collapse="true"}
##### Abstract
Inquiry-based learning as a pedagogical approach encourages students to explore and investigate real-world problems and foster a deeper understanding of concepts as they actively connect new information to their existing mental frameworks (Martell, 2022). Educators are increasingly recognizing the value of creating an engaged learning environment that promotes collaboration and allows for personalized and meaningful learning experiences (Bui & Khuu, 2020). Inquiry-based learning may require that learners engage in networking beyond formal academic settings and connect with professionals, peers, and resources in various fields that could foster their deeper engagement with learning (Robert, 2022).

Open Educational Practices (OEP) tend to create cooperative teaching and learning practices in which the focus is on the role of the learners and the impact that their participation will have on the learning process and practice (Mayrberger, 2020; DeRosa & Robinson, 2017; Author. 2019). Students could benefit from the principles of OEP to engage in open and dynamic conversations to collectively build a deeper understanding of the subject and share their ideas and inquiry work widely while following copyright guidelines. This study, therefore, aspires to investigate the effects of incorporating OEP in an educational environment centred around inquiry.

:::



### Session 4.2  | Transitions of Online Learning and Teaching

**Room 3665 (Session B)**

<a href="https://radio.uvic.ca/public/otessa_4" target="_blank" class="badge bg-primary"><b>Audio Stream 4</b></a>

#### 3:00-3:30 | Connecting in the digital divide: Learners’ experiences of relatedness in a hybrid university course

**Research**

**Behnoosh Khoramrooz $ Mariel Miller** | *University of Victoria*

::: {.callout-note collapse="true"}
##### Abstract

During the global pandemic, the importance of feeling connected and supported in online learning garnered increased attention as learners reported feelings of isolation and loneliness. According to self-determination theory (SDT), “relatedness,” defined as feeling included and related to others, is one of three basic psychological needs. While the prevalence of online, hybrid, and multi-access modes of learning continues to grow post-pandemic, we currently have little understanding of how learners develop feelings of relatedness during online learning or how relatedness can be supported from their perspective.  As such, the purpose of this study is to explore learners’ perceived feelings of relatedness in a large, hybrid, undergraduate course. Specifically, we examined (a) the extent to which learners reported feeling a sense of relatedness in the context of a large hybrid class, and (b) what learners perceive as contributing to their feelings of relatedness. By examining relatedness from learners’ perspectives, findings can advance our understanding of how to ensure students feel a sense of belonging in their online learning and to improve learners’ experience as a consequence.

:::


####  3:30 - 4:00 | Investigating Transformative Technology Integration through Lesson Analysis: A PICRAT Model Pilot Study

<span class="badge bg-danger">Moved to Session 10.1 ()</span>

**Research**

**Adjoa Mensah, Tina Vo, Peter Wiens & Vanessa Vongkulluksn** | *University of Nevada Las Vegas*

::: {.callout-note collapse="true"}
##### Abstract
According to the Council for Accreditation of Teacher Preparation (CAEP), technology integration is an important component of instructional practice and competency standards. This quantitative pilot study evaluates preservice science lesson plans using the nine domains of the PICRAT model. In a university located in the southwest region of the US, researchers piloted the use of the PICRAT model as a metric for the frequency of technology integration occurrences. Coding for PICRAT domains (passive, interactive, creative, replacement, amplification and transformation) was triangulated among researchers using interrater reliability to ensure consistent coding. The researchers deliberated on the particular benefits and obstacles associated with the PICRAT model and offered perspectives on the feasibility of utilizing the domains to code lesson plans in teacher preparation.  These findings suggest a high level of consistency among raters in evaluating different PICRAT domains, particularly in the latter four categories where unanimous agreement was attained.

:::



