# Wednesday, June 19 {.unnumbered}

::: {.callout-tip}
## Note!
Online Only. All times Eastern Daylight Time.
:::

## Current Eastern Daylight Time (click for more info)

<iframe src="https://free.timeanddate.com/clock/i98z8zgl/n165/fs18/tcccc/ftbi/tt0/tw1/tm1/ta1" frameborder="0" width="347" height="23">

</iframe>


<!--
## 11:00 - 11:30 | Co-Located Shared Meet-Up | Drop-In

<a href="https://uvic.zoom.us/j/85851693272?pwd=i3BoOIaTeIsHMrhDaFDYHmpfGMUAnl.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>   <span class="badge bg-info">Host: Meo</span>



## 11:30 - 12:00 | Conference Welcome, Announcements, & Land Acknowledgement
<a href="https://uvic.zoom.us/j/81199937374?pwd=6k5bYLtWaEuroDIjZosPexbBmhKJgM.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>   <span class="badge bg-info">Host: Katy</span>

-->
<!--

## 12:00 - 1:00 | Parallel Session 17 | Invited Speakers

### Invited Speaker Session 17.1 | Forthcoming

<a href="https://uvic.zoom.us/j/82399824423?pwd=0ASQrtippQqIN7b3rWPmR89tgfwpRl.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>    <span class="badge bg-info">Host: Katy</span>





### Invited Speaker Session 17.2 | Forthcoming

<a href="https://uvic.zoom.us/j/88336683214?pwd=GmweELTX5kwbPgcG7JV1qL3ViSbkrm.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>   <span class="badge bg-info">Host: Colin</span>


## 1:00 - 1:15 | Break
-->

## 1:15 - 2:45 | Concurrent Session 18

22.5 Minutes per Presentation

### Session 18.1  | Transitions of Online Learning and Teaching
<a href="https://uvic.zoom.us/j/83030190183?pwd=LmX0TLq8dTu9OF1SHT8xuvmoaBKMvW.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>   <span class="badge bg-info">Host: Katy</span>


#### 1:15 - 1:40 | Reinforcing equity and justice in learning: Using digital co-created rubrics and audio feedback as/for assessment

**Research**

**Nadia Delanoy & Shahneela Tasmin Sharmi** | *University of Calgary*

::: {.callout-note collapse="true"}
##### Abstract

The paper explores a study of a foreign learning experience during the pandemic that was unique due to the co-creative engagement with students. This study examines the effects of using technologically novel feedback strategies and assessment practices to analyze student performance within the frame of the justice theory. Using targeted hybrid means of assessment to provide leveled methods which include auditory and co-created rubric conversations to support bilingual learners in a diverse environment. Qualitatively, using a questionnaire to collect student feedback on co-created decoding of rubrics with thematic analysis and quantitatively using a paired sample t-test by comparing scores for the first draft and the final draft provided fulsome results. Findings indicate how these uses of technology can promote learner autonomy by allowing students to take agency of their own learning and increase students’ performance. The findings reflect the need for using technological avenues to assist bilingual learners in the development of their language skills through extended feedback. 
:::

#### 1:40- 2:05 The Importance of Showing Up (Virtually) : A Duoethnographic Exploration of an Online Doctoral Writing Community of Practice

**Research**

**Nicole Patrie & Danielle Lorenz** | *University of Alberta*

::: {.callout-note collapse="true"}
##### Abstract
Although online discourses about dissertation writing (i.e., you should be writing memes) offer students levity, they function in stark contrast to how dissertation writing is treated in real life.  Canadian education scholars with PhDs have examined the student-supervisor relationship (McAlpine & Weis, 2000), collaborative writing spaces (Eaton & Dombroski, 2022; Ens et al., 2011), and the overall difficulties of the dissertation process (Bayley et al., 2012; Walter & Stouk, 2020), but we have yet to locate literature on the perspectives of Canadian education PhD students who have generated online communities of practice to engage in their dissertation writing. To obtain better understanding of our personal relationships to writing and virtual communities of practice, we established an online writing group during the summer of 2023 where we wrote our respective candidacy proposal and dissertation chapters while also reflecting on and responding to prompts about the process of writing. Using a duoethnographic approach (e.g., Norris et al., 2012; Sawyer & Norris, 2004), we analyzed 76 reflections written over a 13-week period. This research concludes that if PhD students feel un(der)supported by institutional writing communities, or if said communities are not available, constructing their own community will be beneficial to their writing goals.
:::

#### 2:05- 2:25 | The Power of Role Play and Imagination in Online Learning: Exploring Low-Tech Simulation in an HR Capstone

**Practice**

**Lisa Hammershaimb** | *Bellevue University*

::: {.callout-note collapse="true"}
##### Abstract

Asynchronous capstone courses often lack clear opportunities for students to gain confidence in applying skills they’ve learned throughout their program of study. To counteract this, I developed an HR capstone simulation course. Through the experience, I learned the power of low-tech role play to reinvigorate the online capstone experience.

To accomplish this, the course author and I created Jade Stone, a fictional home décor and accessories company and the site of an eight-week simulation. Students entered the simulation as Jade Stone’s new HR manager and were required to solve increasingly complex issues as the company’s new HR Manager. I leveraged my design background to make branding assets and emails, further immersing students. The course author and I developed engaging avatar videos, discussions, and assignments to prepare students for HR careers by integrating academic knowledge with real-world applications.

Student feedback showed the continuity of story arcs and practical application, which made this coursework highly engaging. Developing the simulation was intensely collaborative, requiring meticulous planning to seamlessly embed content without disrupting the fictional world. Though the course took much creative planning, it resulted in a delightful capstone experience that allowed students to gain confidence as they imagined themselves as HR manager.
:::

#### 2:25 - 2:45 | Using a Futures Literacy Framework with Preservice Teacher Candidates

**Research**

**Janette Hughes & Laura Morrison** | *Ontario Tech University*

::: {.callout-note collapse="true"}
##### Abstract
We will share findings from our qualitative case-study research that examined the use of a Futures Literacy (FL) framework with six preservice teacher candidates (PTCs) as they prepared curriculum resources for a series of B.Ed. workshops focused on digital making. The purpose of the study was to encourage the PTCs to consider how they might design educational experiences for their peers that would help them to consider and reflect on how teachers might explicitly foster student confidence, resiliency, flexibility, and adaptability -- key skills needed to thrive in uncertain times. The PTCs engaged in weekly planning sessions over a semester-long internship and each designed a 90-minute workshop for their peers in the B.Ed. program, using a FL framework, combined with an emerging digital technology (Internet of Things; Artificial Intelligence; Robotics, etc.). Data sources include pre-surveys, artefacts they created, and interviews. The findings suggest that being immersed in a project focused on FL helped the PTCs define, analyze, implement and evaluate a FL approach to teaching and learning that helped them think through how they could plan with the notion of a positive future in mind and how they could help their students foster innovation, resilience, flexibility and adaptability.
:::

### Session 18.2 | Wildcard

<a href="https://uvic.zoom.us/j/82914387379?pwd=wdZF3ODHWrLE5MzZ3Yvatv4gUbffCK.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>   <span class="badge bg-info">Host: Meo</span>


#### 1:15 - 2:15 | Design Principles for K-12 Online Learning: A Comparative Review of Standards and Theoretical Models 

**Practice**

**Randy LaBonte** | *Canadian eLearning Network*

**Elizabeth Childs** | *Royal Roads University*

**Michael Barbour** |  *Touro University*


::: {.callout-note collapse="true"}
##### Abstract

In 2023, researchers explored the relationship between Design Principles for K-12 Online Learning (Crichton & Childs, 2022) with quality standards for K-12 online learning, publishing a report on the intersection between design principles and standards (LaBonte, et al., 2023). Design principles refer to the fundamental concepts and guidelines that inform the creation and implementation of educational programs, materials, and systems (Kukulska-Hulme & Traxler, 2013), while standards tend to be more discrete, flexible, and responsive to local conditions (Bell, 2003). The Community of Inquiry (COI), a research-based model describing the three interdependent elements of social, cognitive, and teaching presence (Garrison et al., 2000), was used to explore the intersection points between the COI, design principles, and published standards for K-12 online learning. The analysis was used to create a model to further inform revised design principles and support the ongoing development of quality standards and professional development in K-12 online learning programs in Canada and abroad. It is hoped that basing design principles and standards in the context of a research-based model will further develop an understanding of quality in K-12 online learning that can inform practice.
:::

#### 2:15 - 2:45 | What I Learned Making a Podcast for Peer Review
 
**Practice**

**Brenna Clarke Gray** | *Thompson Rivers University*

::: {.callout-note collapse="true"}
##### Abstract
Podcasting is an equitable vehicle for knowledge translation, but does it “count” as scholarship? Since 2019, I have been part of a SSHRC-funded project to establish a peer reviewed podcasting network in Canada. Over these (more than anticipated) years, I have conceived, planned, recorded, edited, and revised based on reviewer feedback the forthcoming podcast Community of Praxis, a podcast for post-secondary educators. I will share my lessons learned from this experience, including the complexity of adapting the traditional scholarly apparatus to new media forms, the value of research as knowledge mobilization practice, and what is lost in the DIY podcast form when it must conform to the rigours of scholarly evaluation. Attendees will also learn about supports, resources, and proposal processes for those wishing to develop their own scholarly podcast, whether for peer review or not.
:::

### Session 18.3 | Addressing Inequities & Sustaining Positive Change

<a href="https://uvic.zoom.us/j/85361080321?pwd=HMAKHlOPDThCNWQPZ7rl1kBnvpPbIB.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>   <span class="badge bg-info">Host: Colin</span>



#### 1:15 - 2:15 | The Open Book Collective and Thoth: Bringing publishers, libraries and service providers together to establish a shared sustainable open ecosystem for books 

**Practice**

**Judith Fathallah** | *Lancaster University*

**Paula Kennedy** | *University of London Press*

**Lidia Uziel** | *University of California Santa Barbara*

::: {.callout-note collapse="true"}
##### Abstract

This panel will facilitate discussion between representatives from the Open Book Collective,  Thoth Open Metadata, and member librarians and publishers. The Open Book Collective (OBC) is a UK-registered nonprofit focused on delivering new funding streams for OA book publishers and publishing infrastructure providers, reducing the need for Book Processing Charges through unique consortial funding model. The OBC also fosters the sustainability of open infrastructures that make high-quality Open Access books more widely discoverable. One of these, Thoth, a nonprofit Community Interest Company registered in the UK, is a metadata platform and service built on principles of open source and open data.

:::

#### 2:15 - 2:45 | Approaching Openness as a (Critical) Praxis in Higher Education

**Practice** 

**Danielle Dilkes** | *University of Western Ontario*

::: {.callout-note collapse="true"}
##### Abstract

Open education “by its very nature open education [can] not be fully delimited or defined” (Noddings & Enright, 1983). Much of the contemporary discourse in higher educational institutions focuses on open access and the development of open educational resources (OERs); however, in open, openness can go beyond OERs. In this session, we will explore multiple meanings of openness, including open as access, open as affordability, open as autonomy, open as control, open as ambiguity, open as freedom, and other conceptualizations of openness. We will then focus on the potential for openness as a critical praxis that can empower students and transform knowledge practices and infrastructures both within and beyond educational institutions. Throughout the session, we will discuss specific open practices that could function as critical pedagogy and discuss potential barriers to achieving this in higher education; however, this session will largely be focused on provocation and discussion. The intent is not to (re)define the ever elusive term “open” in education, but instead to invite each participant to reimagine what it means to practice openness in their own contexts.
:::

## 2:45 - 3:00 | Break

## 3:00 - 3:45 | Poster Session 19

<a href="https://uvic.zoom.us/j/86496190813?pwd=kEYdFD7WKPWH50WmOic996obPp3I8R.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>   <span class="badge bg-info">Host: Katy</span>

::: {.callout-secondary}
#### Note
There is ONE Zoom link for all Poster Presentations in Session 19.
:::

### Poster Session 19.1 | Wildcard

#### Milton @ Western: An Experiment in Digital Curation with Collection Builder

**Practice**

**Arielle VanderSchans** | *Western University*

::: {.callout-note collapse="true"}
##### Abstract

In response to the growing demand for diverse learning opportunities and innovative assessment methods, our proposal introduces digital curation as an educational tool. Recognized as an active process involving qualitative judgments and contextual organization, digital curation emerges as a solution to bridge the gap between student skill acquisition and faculty assessment goals. 

CollectionBuilder —an open-source framework for crafting digital collection and exhibit websites is powered by metadata and modern static web technology, this tool empowers students with no coding experience to develop essential digital literacies. Activities include creating metadata in a Google Sheet, editing code on GitHub, and selecting data points to construct compelling narratives. 

In an interactive web-based poster session through StoryMaps, we will showcase our digital curation project and share our experience with CollectionBuilder. During this 60-minute drop-in session, we aim to foster dialogue and inspire broader adoption of CollectionBuilder as a teaching aid while answering questions about our project and how this digital exhibit tool can provide an engaging learning experience in humanities education. The StoryMap’s public link ensures accessibility and encourages engagement via social media, using the conference hashtag to extend our reach to a diverse audience.

:::

### Poster Session 19.2 | Transitions of Online Learning and Teaching

#### Exploring Playful Hybrid Teaching Practices in Higher Education: Insights from the Playful Hybrid Higher Education Project

**Practice**

**Sandra Abegglen, Mia Brewster & Sarah Wilkins** | *University of Calgary*

::: {.callout-note collapse="true"}
##### Abstract

The COVID-19 pandemic has necessitated a rapid evolution in teaching methodologies, leading to the widespread adoption of hybrid education - an amalgamation of in-person and online instruction. This paradigm shift has prompted educators to explore innovative approaches to engage students effectively in both virtual and physical learning environments.

The Playful Hybrid Higher Education project seeks to address this challenge by investigating the integration of play and creativity into hybrid teaching practices. Our research focuses on understanding faculty and student experiences within this framework, aiming to provide valuable insights for educators navigating the complexities of hybrid education.

This poster presentation will showcase the findings of our project, which stem from an extensive literature review and surveys conducted among faculty and students. By examining best practices and strategies for incorporating playful elements into hybrid teaching, we aim to contribute to the development of comprehensive guidance for educators in this evolving educational landscape.

As hybrid education emerges as the future of teaching, there is an urgent need for actionable recommendations to support faculty in effectively implementing playful teaching practices. This poster will offer practical insights and recommendations to enhance teaching and learning in the hybrid higher education environment.

:::

### Poster Session 19.3 | Forthcoming
<!-- <a href="https://uvic.zoom.us/j/89134427758?pwd=v9PqDCWe6n0CMXtg1WHkzb10hyr3xr.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>  <span class="badge bg-info">Host: Meo</span>-->

## 3:45 - 4:00  | Discussion/Networking Pod Drop-In
<a href="https://uvic.zoom.us/j/84341354720?pwd=pzwsfWkLSGjEHNgaPHrHxe6s4emn1b.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>  <span class="badge bg-info">Host: Meo</span>


