# Tuesday, June 18 {.unnumbered}

::: {.callout-tip}
## Note!
Online Only. All times Eastern Daylight Time.
:::

## Current time in Montréal (click for more info)

<iframe src="https://free.timeanddate.com/clock/i98z8zgl/n165/fs18/tcccc/ftbi/tt0/tw1/tm1/ta1" frameborder="0" width="347" height="23">

</iframe>


## 11:00 - 11:30 | Co-Located Shared Meet-Up | Drop-In

<!--<a href="https://uvic.zoom.us/j/85851693272?pwd=i3BoOIaTeIsHMrhDaFDYHmpfGMUAnl.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>-->


## 11:30 - 12:00 | Conference Welcome, Announcements, & Land Acknowledgement
<!--<a href="https://uvic.zoom.us/j/83927704159?pwd=7B0OEKVyDtYLEXvKjDdyLA9qVKbd54.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>-->


## 12:00 - 1:00 | Ethics in Design Showcase 15 | Addressing Inequities 

### Showcase 15.1  | Sustaining Positive Change
<!--<a href="https://uvic.zoom.us/j/84931831762?pwd=naZ8ZoUawY4x2E4bEjhEzas4NDwWgi.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>-->



####  A framework and model for engagement in open, online spaces


**Michelle Harrison** | *Thompson Rivers University*

**Michael Paskevicius** | *University of Victoria*


::: {.callout-note collapse="true"}
##### Abstract

This design case provides an analysis of the creation of an innovative open educational practices (OEP) project “Rethink Learning Design”, designed to explore and implement critical approaches to learning and instructional design. We recognized that if we want to embrace the power of OEP to change teaching and learning practice we need to enable spaces that honor multiple voices and perspectives, co-create knowledge and challenge traditional roles and hierarchies supported in open pedagogical approaches. Two key goals guided our project: the development of a reader/resource based on open pedagogy principles, emphasizing inclusivity and participation, and the integration of a reflective practice framework to deepen engagement and bring about a shift in educational practices. In this session and design case we will outline our iterative design process, ethical considerations, and theoretical foundations, and student use and feedback, with the aim of sharing insights and templates for practitioners in diverse educational contexts. We will consider how we can approach design as a theory of action and consider ways to promote learner ownership, open scholarship, anonymity, and options for permanence through our learning design tool.

:::

### Showcase 15.2 | Addressing Inequities
<!--<a href="https://uvic.zoom.us/j/89750976210?pwd=dcbFlhFriqprOwFPwc55y5h4LH9Px5.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>-->


#### Speculative Design and Building a Community of Transformation

**Practice** 

**Kristen Ferris, Vanessa Svihla, Susannah Davis & Nadia Kellam** | *University of New Mexico*

::: {.callout-note collapse="true"}
##### Abstract
Organizational change efforts commonly fail in higher education. Those aimed at diversity, equity, inclusion, and justice (DEIJ) goals face complex barriers, with successful change depending on changes to policies, organizational culture, and norms that disrupt established power dynamics. We argue speculative design is an important tool in such work, enabling change agents to sustain commitment and develop more just visions.

We describe our use of speculative design, remixing, and futurisms in forming a DEIJ-oriented Community of Transformation (CoT) comprising higher education change agents from institutional change leadership teams (e.g., NSF ADVANCE, RED, INCLUDES, etc.) in STEM departments. Using these design tools, we aim to foster change agents’ commitment to and capacity for DEIJ-oriented systems change. We detail precedent - theory and practice - that forms the argument for our design work, with attention to the complex ways that situated understandings of learning, an intersectional approach to power, and organizational change imbue this work. We illustrate our use of speculative design, sharing examples of community building and arts-based activities like trading cards and ‘zines, as well as learning through media clubs. We share successes and challenges, including discomfort with activities that appear to be a step away from academic productivity.

:::


### Showcase 15.3  | Transitions of Online Learning and Teaching
<!--<a href="https://uvic.zoom.us/j/88971747307?pwd=7P4q24rhMOa3H9EapmaLKdrNt8UVDP.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>-->


####  Artifacts from the Futures of Higher Education


**Elisa Arnold, Rocio Chavez Telleria & Laura Viselli** | *eCampus Ontario*


::: {.callout-note collapse="true"}
##### Abstract

How we think about the future informs the decisions we make today; however, it is sometimes difficult to imagine what the future might look like. Foresight is a discipline and methodology that helps us think systematically about possible ways the future might play out and expands the solution space. Experiential futures, a subset of foresight methodology, is way to consider different possible futures by interacting with imagined objects or environments of the future and develops capacity for futures thinking.

The Research and Foresight team at eCampusOntario has created four artifacts, grounded in foresight methodology, capturing different ways one can think about technology in higher education. These artifacts are based on the team’s foresight trend research and explore possible future roles of technology. To facilitate the discussion and support analysis, we will use a foresight informed discussion toolkit developed by our team. This workshop will introduce attendees to the methodology of experiential futures to advance their capacity for futures thinking.

:::



## 1:00 - 1:15 | Break

## 1:15 - 2:45 | Concurrent Session 16

### Session 16.1 | Wildcard
<!--<a href="https://uvic.zoom.us/j/87497487205?pwd=VCbxwNB2RaZ4DhueTW6rfzs0MzrOQU.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>-->


#### 1:15 - 2:15 | Implementing the “Code of Best Practices in Fair Dealing for Open Educational Resources (OER).”
 
**Practice**

**Ann Ludbrook** | *Toronto Metropolitan University*


::: {.callout-note collapse="true"}
##### Abstract

In 2022, the Canadian Association of Research Libraries formed a working group to adapt the US Code of Best Practices in Fair Use for Open Educational Resources. This effort aimed to alleviate the lack of practical guidance available to open educational resource (OER) developers when handling third-party copyrighted material.

The resulting Canadian Code, completed by late 2023, provides a legally sound basis for applying fair dealing in OER creation. This session introduces the Code, focusing on the background of the US and Canadian codes and how they are different, references the legal landscape, discusses the Code's four key use cases and practical application for OER creators, outlines how to implement the code through some examples as well as suggesting institutional adoption strategies. 

This discussion will be led by Ann Ludbrook, Toronto Metropolitan University and include other members of the working group which included Rowena Wake, University of Calgary, Heather Martin, University of Guelph, Josh Dickison, University of New Brunswick, and Stephanie Savage, University of British Columbia. 

The session allows time for comments and questions at the end of presentation to allow for group discussion.

:::

#### 2:15 - 2:45 | Decoding New Literacies: Core Concepts, Competencies, and Outcomes in Algorithm Literacy 


**Research**

**Marta Samokishyn** | *Saint Paul University*

**Rachel Moylan** | *University of British Columbia* 

**Maddie Hare** | *University of Ottawa*

::: {.callout-note collapse="true"}
##### Abstract
Literacy is defined as being deictic in nature, i.e. its definition can “change rapidly as [its] context changes” (Leu et al., 2018, p. 319). As new technologies and social challenges emerge, new literacies appear to respond to the needs, challenges, and opportunities associated with this change, in fact, “new technologies regularly and repeatedly transform previous literacies, continually redefining what it means to become literate” (Leu et al., 2018, p. 327; Lund et al., 2023). 

While algorithm literacy has been talked about for a while, according to Dogruel and colleagues (2022), it is still in its infancy and remains a relatively new field of study.  In fact, while there is an increasing awareness among many about the impact of algorithmic systems on our socio-digital ecosystems, algorithm literacies have not yet been widely incorporated into the corpus of North American post-secondary education (Head et al., 2020). This calls for the increased visibility of algorithm literacy among scholars, as well as clear definitions that could inform the practice.

Thus, this research stems from a pressing need to understand the core elements of algorithm literacy as a growing field. The presenter will provide theoretical findings of a scoping review about functional definitions of algorithm literacy, its’ core concepts, competencies, and outcomes. These theoretical findings of this study will lay the foundation for those who engage in the curriculum development and delivery of algorithm literacy intervention in the educational context. 
:::

### Session 16.2 | Sustaining Positive Change

<!--<a href="https://uvic.zoom.us/j/85150099365?pwd=MwcX8y82861wIEe3qBfc5QYXqsw7DB.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>-->


#### 1:15 - 1:45 | Seeking a newer equity, diversity, and inclusion model for educators

**Practice**

**Lorayne Robertson, Jessica Trinier & Roland Van Oostveen** | *Ontario Tech University*

::: {.callout-note collapse="true"}
##### Abstract
The complexities of the human condition are evident in myriad ways, yet human differences are used globally to deny basic rights. How differences are perceived in education impacts student access and participation in school, and ultimately the outcomes of their school experience. Courses on equity, diversity and inclusion are one means to help future educators become aware that the benefits of schooling are not equally available to all students. This paper presents a reflective description of a model used for the co-construction of equity, diversity and inclusion courses that employs a community of practice model where student voice features prominently in both course design and course enactment. The model relies on establishing a shared spirit of equity humility for learners and educators, and recognition of the need for student safety in potentially uncomfortable conversations. Basic human rights is  an anchoring concept. While, in the past, the teaching of equity has tended to focus on distinct aspects of oppression in society as individual topics, the co-construction of equity model relies, instead, on building bridges of understanding that cross oppressions. The concept of building cross-equity understandings is helpful as a guide to dismantling oppression and guiding the rebuilding of safer, more inclusive spaces in schools.

:::

#### 1:45 - 2:15 | Using compassion as a way forward in the adoption of open education


**Practice**

**Lydia Watson** | *Capilano University*


::: {.callout-note collapse="true"}
##### Abstract

This article explores the use of compassion as an empowering approach to encourage faculty adoption of open educational practices. Despite the growing interest in open education, faculty often face barriers that hinder their engagement. Compassion, as a transformative value, can create an environment of understanding and support among educators.

By cultivating a compassionate culture, faculty can engage in open dialogue, share experiences, and address concerns related to open education adoption. Recognizing individual circumstances and motivations through compassion reduces resistance and fosters openness to change. This article emphasizes the benefits of integrating compassion into open education initiatives.

Drawing on learning theories and digital pedagogies, this article provides practical examples to promote compassion among faculty and support the adoption of open educational resources, open pedagogies, and open-access practices. By embracing compassion, higher education can create an inclusive and supportive environment that encourages faculty to explore and embrace open education.

By recognizing the diverse needs of educators, departments within institutions can foster a compassionate culture that empowers faculty and promotes the benefits of open education. Through compassion, higher education can pave the way for a more open and inclusive educational landscape.

:::

#### 2:15 - 2:45 | Forthcoming

### Session 16.3 | Transitions of Online Learning and Teaching
<!--<a href="https://uvic.zoom.us/j/86735509001?pwd=YR9bma8DmejCHOswwJiCfAMvcUuCae.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>-->


#### 1:15 - 2:15 | Edtech Maker Spaces to Support Sustainable OER Use in Adult Education

**Practice** 

**Jen Vanek, Jennifer Maddrell & Jeff Goumas** |  *World Education & Education Consultants*

::: {.callout-note collapse="true"}
##### Abstract
This presentation addresses the role of Open Education Resources (OER) in inclusively and sustainably supporting adult foundational skills education, and describes a unique professional development (PD) model called “maker spaces”, which boost the capacity of educators to employ OER. 

Access to OER has potential to mitigate the inequitable access to quality instruction in an underfunded public adult education system in the U.S. Adult educators do use OER; however, those available are often designed for other contexts and learners (Newman et al., 2015). Compounding this difficulty, adult education teachers lack expertise, time to develop resources, and access to training (authors, 2023). The “maker space” PD responds to this by working with adult educators to expand their knowledge and skills in discovering, adapting, and producing high-quality and relevant and reusable OER.

Attendees learn about how this research driven service-learning PD has led to construction of an open library of thousands of OER designed to support adult learners. Presenters describe the PD model and the research behind it. They share technical assistance resources developed to help participant educators as they worked together to curate, evaluate, adapt, and create OER. Attendees gain insight into participant experience as they collaborate in a mini “maker space”.

:::

#### 2:15 - 2:45 | Open education and the Ontario governmental postsecondary virtual learning agenda

**Research** 

**Mara De Giusti Bordignon** | *Western University*

::: {.callout-note collapse="true"}
##### Abstract
Open education (OE) is a solution to combat problems of affordability and access in higher education. In Canada, the growing importance of open educational resources and practices is evident through the rising demand for, and expanding availability of, open textbooks and courses. With the growth of OE, Canadian provincial governments and postsecondary institutions have begun to address OE through policy yet there is a gap in our understanding of how OE has become factored into governmental agenda setting for Ontario postsecondary institutions. The main research question asks, how has OE become prominently featured in the Ontario governmental virtual learning agenda in recent years? This study uses a Multiple Streams Approach (MSA) as a method to interrogate five streams, e.g., problem, policy, political, entrepreneurial, and policy window, which converge to influence both agenda setting and decision making. The policy stream enables the analysis of policy documents pertaining to Ontario’s Virtual Learning Strategy (VLS). Preliminary findings identify the role of local and international policy entrepreneurs, and the leveraging of the COVID-19 pandemic as a window of opportunity. This study is significant in its ability to trace contributing factors towards an OE policy agenda for Ontario postsecondary institutions.

:::

## 2:45 - 3:00 | Break

## 3:00 - 3:45 | Unconference
<!--<a href="https://uvic.zoom.us/j/88023225103?pwd=42FIMQqzWdlWX2fbmMTEZEGPMRn1L1.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>-->


## 3:45 - 4:00 | Break

## 4:00 - 4:30 | Social Guest 
<!--<a href="https://uvic.zoom.us/j/83183349119?pwd=C0ayhsTlZ0KSNgg0iiCbpuy3KmOZdP.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>-->


## 4:30 - 5:00 | Discussion/Networking Pod Drop-In
<!--<a href="https://uvic.zoom.us/j/84341354720?pwd=pzwsfWkLSGjEHNgaPHrHxe6s4emn1b.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>-->


