# Friday, June 21 {.unnumbered}

::: {.callout-tip}
## Note!
Online Only. All times Eastern Daylight Time.
:::

## Current time in Montréal (click for more info)

<iframe src="https://free.timeanddate.com/clock/i98z8zgl/n165/fs18/tcccc/ftbi/tt0/tw1/tm1/ta1" frameborder="0" width="347" height="23">

</iframe>



## 11:00 - 11:30 | Co-Located Shared Meet-Up | Drop-In

<a href="https://uvic.zoom.us/j/85851693272?pwd=i3BoOIaTeIsHMrhDaFDYHmpfGMUAnl.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>  <span class="badge bg-info">Host: Meo</span>


## 11:30 - 12:00 | Conference Welcome, Announcements, & Land Acknowledgement
<a href="https://uvic.zoom.us/j/82989966641?pwd=brtnNtb9ywxvMA4bzk1F2AeODmVsao.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>  <span class="badge bg-info">Host: Katy</span>


## 12:00 - 1:00 | Keynote 

<a href="https://uvic.zoom.us/j/87394655143?pwd=cVZHZEl0L3UwVm0yWHVOZFFXbGs3UT09" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>  <span class="badge bg-info">Host: Katy</span>



**Speaker** | *David Wiley*

**Lumen Learning**


### Abstract | Forthcoming


## 1:00 - 1:15 | Break

## 1:15 - 2:45 | Concurrent Session 22

### Session 22.1 | Wildcard & Transitions of Online Learning and Teaching
<a href="https://uvic.zoom.us/j/86483513159?pwd=5y07Mva0zF5n1Fud4mDm851tqgZv3t.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>  <span class="badge bg-info">Host: Katy</span>


#### 1:15 - 1:45 | How instructional designers connect ethics to practice: A discourse analysis | Wildcard

**Research**

**Kanchana Konara & Stephanie Moore** | *University of New Mexico*

::: {.callout-note collapse="true"}
##### Abstract
This study employs discourse analysis to examine how graduate students in instructional design engage in a discussion about ethics on an online discussion board set for a course on ethics and how their discourse on ethics changes over time. It further investigates how instructional designers link ethics and design in their discourse. The discourse analysis is conducted at micro-level (Shawn & Bailey, 2009) using interactional sociolinguistics that focus on meaning-making and interpretation processes (Bailey, 2015) in the discussion board. Discussion is considered an ongoing interactional process where members of the online community respond to each other’s points. 

:::

#### 1:45 - 2:15 | Designing hybrid learning for preservice teachers: Using a community of inquiry framework to increase equitable and inclusive learning environments | Transitions of Online Learning and Teaching

**Practice**

**Nadia Delanoy & Danni Chen** | *University of Calgary*

::: {.callout-note collapse="true"}
##### Abstract
This study investigates the pedagogical and instructional design process of a hybrid course in pre-service teacher education. Guided by the Community of Inquiry (COI) framework, the course design aims to foster social, cognitive, and teaching presence in a hybrid learning environment. A narrative self-study approach was employed to reflect on the teaching practices of an instructor and a graduate teaching assistant (GTA). Data was obtained from their teaching reflections, which examined the impact of implementing a hybrid face-to-face driver model informed by COI on enhancing pre-service teachers' learning experiences. The study results suggest that the hybrid course design provides a more inclusive and empowering learning environment. The flexible format allows students to demonstrate their learning and collaborate effectively while developing socio-emotional awareness. By examining the experiences and knowledge of an instructor and a GTA, this study offers insights into how to effectively incorporate digital technologies and hybrid practices to promote a deeper understanding of lived experience in learning within the context of teacher education programs. With the rapid shift to online learning because of the COVID-19 pandemic, understanding how to design and implement hybrid courses becomes crucial in empowering pre-service teachers for the digital era.
:::

#### 2:15 - 2:45 | Encouraging Academic Writing: Online Graduate Education Writing Retreats | Transitions of Online Learning and Teaching

**Research**

**Connie Blomgren** | *Athabasca University*

::: {.callout-note collapse="true"}
##### Abstract
Graduate students frequently feel pressure to write, and this pressure frequently blocks writing progress. Faculty members also feel a similar pressure to write. Despite the onus upon the individual to produce theses, dissertations, journal articles, or book chapters, the academy has little structural support for authors and even less for affective provisions that inevitably are part of high stakes writing projects. This absence is also within positive psychology where research into the role of encouragement is scant (Wong et al., 2019). To address this lack, I have begun offering online writing retreats for graduate students and faculty. This presentation will describe the organization of the retreats, how I have advertised for attendance, and what happens during the online writing retreats. Using Jensen (2017)as inspiration and guide, these writing retreats have been well received. Both graduate students and faculty members have attended with positive feedback from each offering.

This presentation will cover the pragmatics of these writing retreats and the importance of encouragement as part of academic success(Wong et al., 2019), including scholarly writing. Applying neuroscience findings to the writing process(Bane, 2012; Hanson, 2009, 2013) informs these retreats and contributes to their positive reception.
:::

### Session 22.2 | Sustaining Positive Change
<a href="https://uvic.zoom.us/j/87682931096?pwd=pBz2hEIllG0TOjjTUil6t0v83ARlqz.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>  <span class="badge bg-info">Host: Colin</span>



#### 1:15 - 1:45 | A sensory exploration of inaccessible digital practices: Culturally acceptable marginalization in praxis. 
 

**Research**

**Kim Ashbourne** | *University of Victoria*

::: {.callout-note collapse="true"}
##### Abstract

Globally, post-pandemic researchers in the field of digital accessibility research in education have concluded that despite the potential for information and communication technology (ICT) to remove barriers for learners with disabilities, post-secondary institutions continue to fall short of effectively using ICT to deliver equitable educative experiences to learners with disabilities (Seale, 2020). Digital accessibility frameworks,  checklists, policies and various legislative “sticks” (as opposed to carrots) have been around for decades (Oswal & Meloncon, 2017; Seale, 2004, 2006) but the problem persists. Accessibility and inclusion are viscerally relevant to disabled learners’ lived experience of post-secondary education. Digital accessibility and inaccessibility touch our bodies, minds, ethics, and our sense of self-in-community. This session uses learning artifacts, personal accounts and praxis provocations from the CanDARE.ca praxis project (Ashbourne, 2024) as jumping-off points for group discussions. The goal of this session is to get more people thinking and talking about the role digital inaccessibility plays in the education system’s oppression of learners with disabilities. Furthermore, we need to start talking about the Academy’s complicity in the silent marginalization of people with disabilities in the digital commons.

:::

#### 1:45 - 2:15 | A Flipped Classroom Approach to Paralegal Education


**Research**

**Ashley Stasiewich, Bruce Thomson & Tyra Zaguirre** | *MacEwan University*

::: {.callout-note collapse="true"}
##### Abstract
Legal education traditionally follows two distinct paths, catering to law school students and legal studies majors. However, the training of paralegals, vital contributors to the legal workforce, often lacks comprehensive pedagogical research and effective instructional models. This presentation addresses the gap in legal education for non-lawyers, particularly paralegals, by exploring the implementation of a flipped classroom approach.

Current paralegal programs predominantly focus on clerical skills, leaving a deficit in higher-level legal comprehension and analytical abilities required in the field. Drawing on the success of flipped classroom models in law schools, this study aims to assess whether such an approach can enhance learner engagement and deepen understanding of fundamental legal principles among paralegal students.

Guided by the research question, "Does implementing a flipped classroom instructional approach in an Alberta university legal technology course for paralegals change learner engagement with the fundamental legal knowledge appropriate for paralegals, compared to lecture-based models?" the presentation will share findings from survey data collected in April 2024.

By examining the impact of flipped classrooms on paralegal education, this research contributes to the ongoing discourse on innovative pedagogies in legal instruction. The insights gained from this study can inform curriculum development, address the challenges paralegals face, and ensure they acquire the necessary competencies for success in the legal industry.

:::

####  2:15 - 2:45 | Supporting OER Adoptions through Federated Discoverability

**Practice**

**Don Eldridge** | *eCampus Ontario*

**Mary Gu** | *eCampus Ontario*

**Siri Gauthier** | *eCampus Ontario*

::: {.callout-note collapse="true"}
##### Abstract
A key aspect of supporting OER adoption remains OER discoverability, which is commonly reported as a barrier to OER adoption as part of finding relevant resources and the time required to adopt (Belikov, & Bodily, 2016; Lantrip & Ray, 2021). This open data initiative includes the development of a metadata schema with crosswalks, technical configurations using Open Archives Initiative Protocol for Metadata Harvesting, and a collaborative pilot project to test and implement the technical solution. At the time of this proposal submission, the initiative is federating out the library metadata records to 24 post-secondary institutions. Lessons learned include working with consortiums and shared technology services, evaluating the value of federation for a wide range of post-secondary institutions, and the impact for future collaborations.

:::


### Session 22.3 |Addressing Inequities
<a href="https://uvic.zoom.us/j/83585619817?pwd=sK6NAQUCNbbipUhrBkp5LxgfnNtOS5.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>  <span class="badge bg-info">Host: Meo</span>

####  1:15 - 1:45 | Planning, living, and adding to our plates: K-3 educators' experiences of curricula in Virtual Learning Environments (VLE)

**Practice**

**Melissa Bishop** | *University Prince Edward Island*

::: {.callout-note collapse="true"}
##### Abstract
Virtual Learning Environments (VLE) have interested scholars since the late 20th century, with much of the research focusing on secondary and post-secondary instructors and learners (Brown, 2010; Dabbagh, 2007; Fuchs, 2014; Plump & LaRosa, 2017; Proserpio & Gioia, 2007). With the onset of VLEs in elementary education due to the COVID-19 pandemic and the continuation of synchronous virtual learning thereafter, VLEs have become commonplace in K-3 contexts across Ontario. Yet, as we contend with the ubiquitous nature of technology in early elementary, a paucity of literature exists regarding teachers’ and Early Childhood Educators' (ECE) experiences of planned and lived curricula (Muldong et al., 2021; Aperribai et al., 2020; Ferdig et al., 2020) in VLEs. Starting from standpoint epistemologies (Au, 2012; Harding, 1991; Haraway, 2003), reflecting on five narrative interviews, and employing a narrative analysis of field texts (Clandinin, 2006; Clandinin & Connelly, 1988, 1996, 2000), we unearthed six narrative threads: time, parent communication, relationship building, classroom community, engagement and teacher presence, and technological challenges. These six threads suggested how ECEs and teachers navigated the entanglements of planned and lived curricular experiences in VLEs. Further, the five threads exposed critical elements to be considered in future VLE policy and curricular reform in the K-3 context.

:::




#### 1:45 - 2:15 | Incorporating Open Educational Technology for Designing Diversity, Equity, and Inclusion Learning Experiences 

**Practice**

**Caroline Chance** | *California Polytechnic State University*

::: {.callout-note collapse="true"}
##### Abstract

The increasing number of English as a Second Language (ESL) students seeking education, the escalating costs of tuition, and the high proportion of students from racial minorities dropping out call for course content that is accessible, affordable, and all-embracing. First, recent studies have consistently found that most Open Educational Resources (OER) are designed for learners with advanced levels of English proficiency, which counters the purpose of offering curriculum to the general public. First-generation students and immigrant students are disproportionally disadvantaged by not having early exposure to terminology spoken by family members working in specialized professions such as law or medicine. Second, annual statistics have repeatedly shown the costs of tuition at both public and private universities rising faster than inflation, which reverses the improvements that higher education has made for decades in creating pathways. The decreasing affordability of attending college has negatively impacted under-sourced students who did not come from families that can provide financial support or graduated from school districts that could find funding sources. Third, the Department of Education findings indicate the high dropout rates among under-represented students, such as Latinx males and Black males due to monetary and mental health issues. The lack of representation in textbooks and case studies has resulted in a learning environment that is devoid of the multiplicity of ideas and acknowledgment of different cultural influences. In this session, the presenter will provide strategies for course materials that integrate common English, everyday application assignments, and examples that resonate with students.

:::

#### 2:15 - 2:45 | Flexibility and Foresight in Ontario Postsecondary Education: Voices from the Field

<span class="badge rounded-pill bg-danger">Moved from Session 8.2</span>

**Practice**

**Elisa Arnold, Rocio Chavez Telleria & Laura Viselli** | *eCampusOntario*

::: {.callout-note collapse="true"}
##### Abstract
Flexibility has emerged as a key area to support digital transformation in postsecondary education, and educators are often at the forefront of implementation. To understand how educators are thinking and feeling, we engaged with 45 educators from Ontario's publicly-supported postsecondary institution through six virtual workshops using foresight methods to frame the conversations. Foresight is a formal, systematic way of thinking about the future, which offers a way to think about how the future might play out and expand the solution space. Specifically, we used the following foresight methods: Futures Triangle, to understand the interrelationships among future visions, present drivers of change, and past limitations; Causal Layered Analysis (CLA), to explore the assumptions that underlie the way we frame problems, situations, and solutions; and Three Horizons, to explore what would it take to transition from present situations to future visions. This presentation is a summary of the research about these educators think and feel about flexibility in post secondary education, including considerations of equity and ethics and the application to practice, policy and infrastructure and recommended next steps.
:::
## 2:45 - 3:00 | Break

## 3:00 - 3:45 | Closing Comments
<a href="https://uvic.zoom.us/j/88689163871?pwd=yqOhnHJu4HoVy8bhkAH3xeiJ18tQln.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>  <span class="badge bg-info">Host: Katy</span>


## 3:45 - 4:00 | Discussion/Networking Pod Drop-In
<a href="https://uvic.zoom.us/j/82508595259?pwd=o4592y2wE2B13LPtX5chWUMoKBr7O1.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>  <span class="badge bg-info">Host: Meo</span>
