# Thursday, June 20 {.unnumbered}

::: {.callout-tip}
## Note!
Online Only. All times Eastern Daylight Time.
:::

## Current Eastern Daylight Time (click for more info)

<iframe src="https://free.timeanddate.com/clock/i98z8zgl/n165/fs18/tcccc/ftbi/tt0/tw1/tm1/ta1" frameborder="0" width="347" height="23">

</iframe>

<!--
## 11:00 - 11:30 | Co-Located Shared Meet-Up | Drop-In

<a href="https://uvic.zoom.us/j/85851693272?pwd=i3BoOIaTeIsHMrhDaFDYHmpfGMUAnl.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>  <span class="badge bg-info">Host: Meo</span>


## 11:30 - 12:00 | Conference Welcome, Announcements, & Land Acknowledgement
<a href="https://uvic.zoom.us/j/85335383554?pwd=SGSXw2HLTVeeYu0ow1ofaSMXTNiuri.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>  <span class="badge bg-info">Host: Katy</span>
-->


## 12:00 - 1:00 | Ethics in Design Showcase 20

<a href="https://uvic.zoom.us/j/89526445493?pwd=JwWGaJ9vuQSQQHlOHoUJOwbG8xC0BX.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>  <span class="badge bg-info">Host: Katy</span> 

::: {.callout-dark}
#### Note
There is ONE Zoom link for all Ethics in Design Showcases in Session 20.
:::
### Showcase 20.1 | Sustaining Positive Change
<a href="https://otessa.org/ethicsindesign/2024/06/09/ethics-of-consuming-devices/" target="_blank" class="badge bg-warning"><b>Link to Post</b></a>

#### Redesigning Computing for Openness - the Ethics of Consuming Devices 

**Brian Sutherland** | *University of Toronto*

::: {.callout-note collapse="true"}
##### Abstract

Have you started to accumulate old computing devices?   Why does the logic of computing involve repeated purchase and consumption of expensive "molded plastic epics" (Gabrys, 2011)?  Thinking back on calculation devices and this ethical problem of repeated consumption, the simple solar calculator stands out for its durability -- an energy harvesting strategy that doesn't use batteries, and it doesn't wear out.  Fifty year old solar powered calculators and other electronic devices which still work may be found. In this session, proposed for the Ethics in Design Conference Strand, I will review the history of energy harvesting information devices and their significant characteristics around sustainability, present response designs which engage various ethical questions around consumption, carbon production and degrowth, and discuss their usefulness as open designs and thought-artifacts in an iterative speculative design conversation around climate change.
:::

### Showcase 20.2 | Addressing Inequities
<a href="https://otessa.org/ethicsindesign/2024/06/09/open-learning-design-in-context/" target="_blank" class="badge bg-warning"><b>Link to Post</b></a>

#### Open Learning Design in Context: Expanding the Continuum

**Research**

**Verena Roberts** | *University of Calgary*

**Michelle Harrison** | *Thompson Rivers University*

::: {.callout-note collapse="true"}
##### Abstract
Our conceptual paper examines open-learning approaches from a design perspective that takes a more systematic view which is not intended to promote the replication of open-learning design models. Instead, this paper is written to highlight how educators can find connections and possible integration to their own learning contexts to design with principles that could lead to more equitable, accessible and responsive learning environments for all learners. The Open Learning Design Continuum (OLDC) is an ever-changing and evolving collaborative learning design model that examines the potential principles of open learning design in multiple higher education contexts. Through a comparison of case studies of open curriculum designs at two Canadian HE institutions, we will examine ways that educators and learners have experienced a variety of approaches to open learning design, including the blurring of informal/formal spaces, the uses of open educational resources (OER) and open platforms to create more student-centered, equitable and accessible learning spaces.

:::

### Showcase 20.3 | Addressing Inequities

<a href="https://otessa.org/ethicsindesign/2024/06/09/speculative-design-in-a-summer-camp/" target="_blank" class="badge bg-warning"><b>Link to Post</b></a>

#### Speculative Design in a Summer Camp: Tensions around Infantilization

**Research**

**Madalyn Wilson-Fetrow** | *University of New Mexico*

::: {.callout-note collapse="true"}
##### Abstract
Summer camps offer opportunities for youth to learn technical skills and apply them in service of solving wicked problems, like climate change and social/economic injustices. While many camps want youth to bring their experiences, they anticipate that campers will share happy or optimistic experiences, contributing to a sense of hopeful, if idealistic and unrealistic solutions to pressing issues. Those who administer and facilitate such learning experiences encounter youth who passionately want to tackle these problems, but who are not naïve regarding the harms surrounding climate disaster and racial injustice.

In this session, we present examples of design challenges that—through participants’ perspectives and an ideation technique—became more speculative and critical. We supported our middle school participants to use the Wrong Theory Protocol to generate harmful and humiliating ideas prior to generating beneficial solutions. In doing so, some facilitators—who came from higher SES settings than the campers—became uncomfortable with the darkness of participants’ ideas, which included policy brutality, gun violence, etc., and stemmed from their everyday experiences of poverty. In this way, facilitators’ infantilization of participants is a tension present in many such designs, and one which we aim to trouble, using structural analysis of videos and artifacts.
:::

## 1:00 - 1:15 | Break

### Session 21.1  | Wildcard & Addressing Inequities

<a href="https://uvic.zoom.us/j/87420104805?pwd=j76DBoaiu950OEOC1dHXgiRk8aXIsy.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>  <span class="badge bg-info">Host: Meo</span>


#### 1:15 - 2:15 | Graphically Speaking: Sketchnotes in an Open Educational Practice

**Workshop**

**Helen DeWaard** | *Lakehead University*

**Debbie Baff** | *Joint Information Systems Committee (JISC)*

**Giulia Forsythe** | *Brock University*

::: {.callout-note collapse="true"}
##### Abstract

The application of graphic visualization can be used by open educational practitioners, scholarly writers, and researchers to illustrate mental models, enhance sense making, and extend memory. Although the presenters will share their collaborative autoethnographic research as they examined theoretical frameworks that relate to their graphic visualization practice of sketchnoting, the primary focus of this workshop is on the practice of sketchnoting in academia. Definitions of sketchnoting, open educational practices, and hupomnemata are provided, and theoretical frameworks are shared. This is followed by brief descriptions of the presenters’ individual contexts and sketchnoting stories. In this way, the authors advocate for and explain why and how sketchnotes are part of their open educational practice. The presenters will actively engage participants in sketchnoting experiences and identify issues when sketchnoting in an academic writing practice. The authors identify issues and challenges, offer tips to begin sketchnoting, and outline how sketchnoting can expand the landscapes of academic writing. 
:::

#### 2:15 - 2:45 | The metadata of translation: Navigating changes to metadata for informed consent in OER translation

**Practice**

**Siri Gauthier** | *eCampusOntario*

::: {.callout-note collapse="true"}
##### Abstract
This session discusses metadata’s role in accurately reflecting open education resources (OER) and its role in ensuring linguistically and culturally sensitive practices.

A recent initiative by an Open Education Resources (OER) repository in Ontario to provide large scale translation of existing OER to serve its francophone linguistic minority community and the related metadata changes that this project necessitated will be the heart of the discussion. As part of an effort to ensure resources were created, and recognizing the often-limited capacity for authorship, various modes of translation were considered. As part of this effort, metadata had to reflect the need for potential users to opt-in to materials that were not sensitive to their unique linguistic needs and the realities of the lived experiences of either themselves or their learners.

Ethical considerations surrounding informed consent will be scrutinized, highlighting tailored strategies for obtaining meaningful consent within the unique cultural and linguistic context of the French minority population in Ontario. Attendees can anticipate an insightful session that unpacks the intricate connections between translation, metadata, and informed consent, with a nuanced focus on the multilingual landscape of OER and the linguistic diversity of the French minority in Ontario.

:::


### Session 21.2  | Transitions of Online Learning and Teaching
<a href="https://uvic.zoom.us/j/88306702519?pwd=36SG6yyRGLhWa6QHSS8irGphQ1l3KN.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>  <span class="badge bg-info">Host: Katy</span>


#### 1:15 - 2:15 | FLO Fusion – A Sustainable Approach to Supporting Professional Development with OERs 

**Practice**

**Helena Prins** | *BCcampus*

::: {.callout-note collapse="true"}
##### Abstract

In the face of multifaceted challenges confronting higher education globally, strategic professional development becomes paramount. Economic, social, technological, demographic, environmental, and political dynamics necessitate a resilient sector capable of delivering quality education. The profound impact of the global pandemic on the Canadian post-secondary system has accentuated issues like the digital divide and online learning readiness. Recent research underscores that overwhelm, burnout, and negative faculty perceptions about online learning persist; faculty and students desire more technology supported learning, but does faculty have the skills and "know how" to teach in digital environments?

This presentation emphasizes the strategic utilization of existing open education resources (OERs) for professional development in preparing and supporting faculty to navigate our complex post-secondary context. A curated collection of OERs under the Facilitating Learning Online (FLO) umbrella will be introduced. These resources cover a diverse array of topics, including Indigenizing pedagogy, Artificial Intelligence exploration, and Anti-racism strategies, providing a robust foundation for professional development. 

Attendees will 1) gain a deeper understanding of how FLO OERs enhance teaching resilience in higher education, 2) explore FLO content for professional development, and 3) discuss strategies for OER adoption locally.
:::

#### 2:15 - 2:45 | Realities of Remote Learning: Autistic Youths’ Experiences During COVID-19

**Research**

**Millie Batta** | *Shoreline Counselling*

::: {.callout-note collapse="true"}

School closures due to the COVID-19 pandemic resulted in a shift to emergency remote learning, significantly impacting autistic students who experienced interruptions to school-based supports and social interactions. Using the framework of thriving, this research study explored the experiences of autistic youths and their mothers of emergency remote learning during the first few months of the pandemic, with a focus on well-being. The findings of this study highlighted how remote schooling came with a spectrum of benefits and challenges. The autistic youths’ experiences of remote schooling are described through three common themes: (1) social, (2) emotional, and (3) academic. This research aligns with the conference’s subtheme of online learning and teaching as it aims to integrate the learnings from students’ remote schooling experiences for inclusive practices for neurodiverse students. This presentation considers how online learning may impact the social engagement and overall well-being of autistic youth. I conclude the session by highlighting how professionals working with autistic youths may benefit from understanding their remote schooling experiences using a thriving framework to better support their social, emotional, and educational needs in future online settings.

:::

### Session 21.3 | Sustaining Positive Change
<a href="https://uvic.zoom.us/j/89800215355?pwd=jj0UbzmfDOI0y0mOxaPIc2zFfwkAhR.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>  <span class="badge bg-info">Host: Colin</span>


#### 1:15 - 2:15 | A world of pure imagination: scaling learning design with a design system 


**Workshop** 

**Joyce Seitzinger** | *RMIT Online*

::: {.callout-note collapse="true"}
##### Abstract
In the post-pandemic era, educational institutions face the critical task of scaling up digital learning options. This transition reveals a fundamental challenge: bespoke design, the traditional approach in academia, is not scalable. To address this, our workshop introduces design systems as a scalable framework for crafting digital learning experiences. Attendees will learn from experts and case studies across industries, understanding how reusable components and clear standards not only streamline the development process but also ensure consistency and facilitate cross-disciplinary collaboration. Key objectives include mastering design system fundamentals, overcoming bespoke design limitations, and fostering innovation within education.

:::




#### 2:15 - 2:45 | Power to the People: Digital Humanities for/as Community Development

**Research**

**Keith Cheng** | *University of Toronto*

::: {.callout-note collapse="true"}
##### Abstract
“Digital Humanities” (DH) has been a rapidly growing field within academia, used to broadly describe scholarship situated in the intersection of technology and the humanities. While the field was originally conceptualized with radical intentions to move toward “the democratization of culture and scholarship” (Schnapp and Presner, 2009), it has become increasingly institutionalized and largely detached from these radical origins. In a time where there is there is a growing digital divide (Darko et al., 2023) and heightened concerns around the harmful impacts of new technologies (Benjamin, 2019), imagining new futures for the field of digital humanities is crucial. Putting digital humanities in conversation with scholarship from the fields of human and community development, the author argues that digital humanities is a radical site of possibility where agency and solidarity can be developed (Bhattacharyya, 2004), understandings of the self and one’s position within the larger world can be negotiated (Collins, 2006; Freire, 1968), and power can be decentralized from the university.

The author employs Nancy Fraser’s theory of justice to develop a framework for equitable digital humanities work, discussing tangible strategies and potential barriers to its application through an autoethnographic account of their experiences developing digital humanities programming for underrepresented students at a Historically Black College/University (HBCU). The paper will discuss both the process and product of digital humanities, exploring how the process of doing digital humanities can have transformative impact for those involved and how new technologies can help facilitate wider and more diverse public engagements with digital humanities work.
:::

## 2:45 - 3:00 | Break

## 3:00 - 4:00 | Study on the Ways of Conferencing for OTESSA 2.0

<a href="https://uvic.zoom.us/j/88962802906?pwd=G9Q0x3CycSKgor5U1GAjuNv0gg76F2.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>  <span class="badge bg-info">Host: Katy</span>

<span class="badge bg-danger">NEW</span>

**Hongran Cui** | *Thompson Rivers University*

**Valerie Irvine** | *University of Victoria*

**Connie Blomgren** | *Athabasca University*

**Mariel Miller** | *University of Victoria*

**Stephanie Moore** | *University of New Mexico*

**Colin Madland** | *University of Victoria*

::: {.callout-note collapse="true"}
##### Abstract

Focus Group for OTESSA 2.0: Collecting Research on Ways of Conferencing

You are invited to engage in a focus group session exploring the future of conferencing. This focus group is part of a research project, exploring the evolving landscape of academic conferencing in the context of continuous technological advancements, societal changes, and climate concerns. Conference attendees are invited to review the [study overview and consent form](https://ca.research.net/r/OTESSAsurvey). Those who wish to participate are welcome to come discuss your preferences, experiences, and expectations. The session will be audio recorded for transcription, but not streamed. Through this structured discussion, we aim to gain a comprehensive understanding of how conferencing can meet the needs of diverse participants in environments that can range from nature-based to digital, online, and open contexts. We look forward to identifying challenges and opportunities that will shape OTESSA 2.0.
:::

<!--
## 3:45 - 4:00 | Discussion/Networking Pod Drop-In

<a href="https://uvic.zoom.us/j/84341354720?pwd=pzwsfWkLSGjEHNgaPHrHxe6s4emn1b.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>   <span class="badge bg-info">Host: Meo</span>



### Showcase 20.3 | Addressing Inequities
<a href="https://uvic.zoom.us/j/89526445493?pwd=JwWGaJ9vuQSQQHlOHoUJOwbG8xC0BX.1" target="_blank" class="badge bg-success"><b>Link to Zoom</b></a>


#### Bringing Human-centeredness Learning Analytics Dashboards: Design Principles and Implications

**Practice**

**Dana Al Zoubi, Noah Glaser & Evrim Baran** | *Mississippi State University*

::: {.callout-note collapse="true"}
##### Abstract
The rise of Learning Analytics (LA) applications, particularly Learning Analytics Dashboards (LADs), offers immense potential to improve teaching and learning outcomes. However, challenges persist in the effective design, ethical use, and privacy considerations associated with LADs. This paper explores the growing interest in LADs and emphasizes the need for a human-centered approach to address design and structural challenges. The proposed human-centered design (HCD) approach advocates for prioritizing end-user's perspectives and needs throughout the design process, incorporating transparency, inclusion, and accountability principles. This paper delves into the implications of adopting HCD principles, such as personalized learning experiences, inclusive representation, improved learner engagement, and ethical use of data. By involving stakeholders, especially learners, in the design process, LADs can be tailored to diverse needs and preferences, promoting engagement and informed decision-making. The discussion extends to transparency, inclusion, and accountability as key principles for addressing ethical and privacy concerns associated with LADs. Future research directions are proposed to further explore the effective application of human-centered approaches in LAD design, aiming to continually enhance their role in promoting positive learning outcomes in educational settings.

:::
-->

<!--
#### 2:15 - 2:45 |  Augmented Reality to develop learning tool for students: Transforming cell phones into flashcards


**Practice**

**Nazlee Sharmin** | *University of Alberta*

::: {.callout-note collapse="true"}
##### Abstract
Traditional flashcards are one of the most popular and optimized ways to learn factual knowledge and improve memory performance. However, this method is helpful only for motivated students because the amount and timing of flashcard use are critical for success. We have used augmented reality (AR) to develop an app called ‘Dental AR’ that allows students to use their smartphones as flashcards. Using this app, students can learn and self-test their knowledge at a time and place that is convenient for them. We used Unity3D with Vuforia to develop Dental AR. Oral histology glass slides were scanned and converted to digital images to generate target images. Annotated versions of the slides were used as output for the corresponding target images. To understand user experiences and satisfaction with Dental AR, first-year dentistry students were invited to complete an online survey. The survey results indicated an overall satisfaction with Dental AR and willingness to use similar applications in other subjects. 
:::

-->

<!--
### Showcase 24.2 | Wildcard
#### Becoming Alive Together: Towards a “Carrier Bag” Approach to Ethical Learning Designs


**Research** 

**Beth Giebus-Chavez** | *University of New Mexico*

::: {.callout-note collapse="true"}
##### Abstract
Sustainable responses to overlapping social, economic, and environmental crises require a recognition of the interconnected and systemic nature of planetary concerns. Yet traditional instructional design frameworks offer a linear, hero-centered narrative that undermines the collective changes needed to address complex issues. In this conceptual paper, I propose an alternative approach to learning design that integrates Le Guin's Carrier bag theory of fiction (1989/2019) and affirmative ethics (Braidotti, 2015)  By recognizing the entanglements of human and non-human elements within the online environment, the ‘carrier bag’ decenters the traditional notion of a solitary hero—whether teacher, learner or designer—in navigating a predetermined path. Instead, the focus shifts towards a dynamic and inclusive learning assemblage that is attuned to the relational capacities of its members. Key to such a move is the acknowledgment of the vital, participatory role of digital objects. I outline five provocations—care, complexity, complicity, collaboration, and care—that can be applied to the design of online courses to deepen awareness of the relationship between digital objects and ecological responsiveness. Grounded in material-discursive practices and posthuman ethics, this study contributes to ongoing discussions of innovative design paradigms that better align with the complexities of contemporary education.

:::

-->